"""Browser evidence for a golden run, taken independently of the pipeline.

After the workflow ends, the harness plays the game again itself:

1. A scratch clone of the game repository at its HEAD (`git clone`, local, no network), in
   <workdir>/evidence/browser-<game>/checkout - the game repository is never touched.
2. Dependencies from the warm pnpm store (`pnpm install --frozen-lockfile --offline`).
3. The bundle: the RELEASED package when release drafted one - the primary platform's zip
   from release/<id>/, checked against the manifest's sha256 and unpacked as dist/, so the
   bytes played are the bytes that would ship - else a fresh `pnpm build` of the commit,
   and the evidence says which.
4. The game's own Playwright suites, desktop and mobile (the template's smoke plus the
   ported example's aspect-tagged spec), JSON reporter.
5. The harness's own probe (browser/probe.spec.ts), per viewport: boot, the engine and
   platform the template's `window.__wgf__` probe reports, start through a real click,
   frames rendering, game over, restart; screenshots hashed; console and page errors and
   every external request recorded (they are aborted - it never contacts a portal).

Every child goes through wgflib.procs, so nothing it starts outlives it.
"""

import hashlib
import json
import os
import shutil
import socket
import zipfile

from wgflib import procs

HERE = os.path.dirname(os.path.abspath(__file__))
PROBE_SPEC = os.path.join(HERE, "browser", "probe.spec.ts")

GOLDEN_CONFIG = """\
// Generated by the Factory's golden-run harness (scripts/golden/browser.py) in a scratch
// clone. Serves the bundle under dist/ with the repository's own `pnpm preview`.
import {{ defineConfig, devices }} from "@playwright/test";

export default defineConfig({{
  testDir: "tests/golden",
  outputDir: "test-results/golden",
  workers: 1,
  retries: 0,
  reporter: [["list"]],
  use: {{ baseURL: "http://localhost:{port}" }},
  projects: [
    {{ name: "desktop", use: {{ ...devices["Desktop Chrome"] }} }},
    {{ name: "mobile", use: {{ ...devices["Pixel 5"] }} }},
  ],
  webServer: {{
    command: "pnpm preview --port {port} --strictPort",
    port: {port},
    reuseExistingServer: false,
    timeout: 120_000,
  }},
}});
"""


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return "sha256:" + digest.hexdigest()


def free_port():
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]


def _run(argv, cwd, timeout, env=None, log=None):
    result = procs.run(argv, cwd=cwd, timeout=timeout, env=env, log_path=log,
                       stderr_to_stdout=True)
    return {"argv": " ".join(argv), "status": result.status, "returncode": result.returncode,
            "ok": result.ok, "killed": list(result.killed or []),
            "tail": result.tail(30) if not result.ok else None}


def released_package(repo, release):
    """(zip path, recorded checksum) of the primary platform's package, or (None, None)."""
    if not release or not release.get("manifest_path"):
        return None, None
    packages = release.get("packages") or []
    primary = release.get("primary_platform")
    chosen = next((p for p in packages if p.get("platform_id") == primary), None) or (
        packages[0] if packages else None)
    if not chosen or not chosen.get("path"):
        return None, None
    return os.path.join(repo, chosen["path"]), chosen.get("checksum")


def _unpack(zip_path, target):
    shutil.rmtree(target, ignore_errors=True)
    os.makedirs(target)
    with zipfile.ZipFile(zip_path) as archive:
        for name in archive.namelist():
            if name.startswith("/") or ".." in name.split("/"):
                raise ValueError(f"{zip_path}: unsafe entry {name!r}")
        archive.extractall(target)


def _suite_results(report_path):
    try:
        with open(report_path, encoding="utf-8") as handle:
            report = json.load(handle)
    except (OSError, ValueError):
        return None
    tests = []

    def walk(suite, trail):
        for spec in suite.get("specs") or []:
            for test in spec.get("tests") or []:
                tests.append({"file": spec.get("file") or suite.get("file"),
                              "title": spec.get("title"),
                              "project": test.get("projectName"),
                              "status": test.get("status")})
        for child in suite.get("suites") or []:
            walk(child, trail + [child.get("title")])

    for suite in report.get("suites") or []:
        walk(suite, [suite.get("title")])
    counts = {}
    for test in tests:
        counts[test["status"]] = counts.get(test["status"], 0) + 1
    return {"total": len(tests), "counts": counts,
            "passed": bool(tests) and all(t["status"] in ("expected", "flaky") for t in tests),
            "projects": sorted({t["project"] for t in tests if t["project"]}),
            "failed": [t for t in tests if t["status"] not in ("expected", "flaky", "skipped")],
            "report_sha256": sha256_file(report_path)}


def capture(game, repo, evidence_dir, run_id=None, release=None, env=None):
    """Play the game; return the browser evidence as a dict (also written as JSON)."""
    base = os.path.join(evidence_dir, f"browser-{game.key}")
    shutil.rmtree(base, ignore_errors=True)
    checkout = os.path.join(base, "checkout")
    os.makedirs(base)
    log = os.path.join(base, "commands.log")
    evidence = {"game": game.key, "title_id": game.title_id, "run_id": run_id,
                "expected_engine": game.engine, "commands": []}

    head = procs.run(["git", "-C", repo, "rev-parse", "HEAD"], timeout=30)
    evidence["commit"] = head.stdout.strip() if head.ok else None
    steps = evidence["commands"]
    steps.append(_run(["git", "clone", "--quiet", "--no-hardlinks", repo, checkout], base, 300,
                      env, log))
    if not steps[-1]["ok"]:
        return _finish(evidence, base)
    steps.append(_run(["pnpm", "install", "--frozen-lockfile", "--offline"], checkout, 900,
                      env, log))
    if not steps[-1]["ok"]:
        return _finish(evidence, base)

    zip_path, recorded = released_package(repo, release)
    if zip_path and os.path.exists(zip_path):
        actual = sha256_file(zip_path)
        evidence["bundle"] = {"source": "release-package",
                              "path": os.path.relpath(zip_path, repo), "sha256": actual,
                              "recorded_sha256": recorded,
                              "matches_manifest": recorded == actual}
        # The packages keep dist/ built by the repo's own scripts (packages/* dist is still
        # needed by nothing at runtime: the bundle is self-contained).
        _unpack(zip_path, os.path.join(checkout, "dist"))
    else:
        evidence["bundle"] = {"source": "rebuilt-from-commit",
                              "note": "release drafted no package in this run"}
        steps.append(_run(["pnpm", "run", "build"], checkout, 900, env, log))
        if not steps[-1]["ok"]:
            return _finish(evidence, base)

    # The game's own suites, against that bundle.
    suite_report = os.path.join(base, "suites.json")
    suite_env = dict(env or os.environ)
    suite_env.update({"PLAYWRIGHT_JSON_OUTPUT_NAME": suite_report,
                      "PW_OUTPUT_DIR": os.path.join(base, "suites-output")})
    suites = _run(["pnpm", "exec", "playwright", "test", "--project", "desktop", "--project",
                   "mobile", "--reporter=json"], checkout, 900, suite_env, log)
    steps.append(suites)
    evidence["suites"] = _suite_results(suite_report) or {"passed": False,
                                                          "note": "no JSON report"}
    evidence["suites"]["exit"] = suites["status"]

    # The harness's own probe.
    os.makedirs(os.path.join(checkout, "tests", "golden"), exist_ok=True)
    shutil.copyfile(PROBE_SPEC, os.path.join(checkout, "tests", "golden", "probe.spec.ts"))
    port = free_port()
    with open(os.path.join(checkout, "playwright.golden.config.ts"), "w",
              encoding="utf-8") as handle:
        handle.write(GOLDEN_CONFIG.format(port=port))
    probe_out = os.path.join(base, "probe")
    probe_env = dict(env or os.environ)
    probe_env.update({"GOLDEN_GAME": game.key, "GOLDEN_PROBE_OUT": probe_out})
    probe = _run(["pnpm", "exec", "playwright", "test", "-c", "playwright.golden.config.ts"],
                 checkout, 600, probe_env, log)
    steps.append(probe)
    evidence["probe"] = _probe_results(probe_out, probe)
    return _finish(evidence, base)


def _probe_results(out, run):
    viewports = {}
    for project in ("desktop", "mobile"):
        path = os.path.join(out, project, "probe.json")
        try:
            with open(path, encoding="utf-8") as handle:
                data = json.load(handle)
        except (OSError, ValueError):
            viewports[project] = {"passed": False, "note": "probe wrote no result"}
            continue
        data["screenshot_sha256"] = {
            name: sha256_file(shot) for name, shot in (data.get("screenshots") or {}).items()
            if os.path.exists(shot)}
        data["screenshots"] = {name: os.path.relpath(shot, out)
                               for name, shot in (data.get("screenshots") or {}).items()}
        steps = data.get("steps") or {}
        data["passed"] = (all(steps.get(k) for k in ("boot", "start", "renders", "game-over",
                                                     "restart"))
                          and not data.get("page_errors"))
        viewports[project] = data
    engines = sorted({(v.get("probe") or {}).get("engine") for v in viewports.values()
                      if v.get("probe")})
    return {"exit": run["status"], "viewports": viewports,
            "engine_reported": engines[0] if len(engines) == 1 else engines,
            "passed": run["ok"] and all(v.get("passed") for v in viewports.values())}


def _finish(evidence, base):
    suites = evidence.get("suites") or {}
    probe = evidence.get("probe") or {}
    evidence["engine_matches"] = probe.get("engine_reported") == evidence["expected_engine"]
    evidence["passed"] = bool(suites.get("passed") and probe.get("passed")
                              and evidence["engine_matches"]
                              and (evidence.get("bundle") or {}).get("matches_manifest", True))
    evidence["console_errors"] = sorted({e for v in (probe.get("viewports") or {}).values()
                                         for e in v.get("console_errors") or []})
    with open(os.path.join(base, "browser-evidence.json"), "w", encoding="utf-8") as handle:
        json.dump(evidence, handle, indent=2, sort_keys=True)
        handle.write("\n")
    return evidence
