"""The playability step: the build is played from outside before anyone calls it playable.

    prototype-report (commit) + game-design (experience contract) + scaffold-record
      -> clone that commit into scratch, install, build (the game repository's own pnpm)
      -> bot.spec.ts on desktop and mobile viewports, behind the refusing network proxy:
         four fresh first sessions - idle, act, win (oracle), lose and retry (anti-oracle)
      -> analysis.judge: the checks, against build_spec.experience and the bars
      -> playability-report

    PASS      every required check passed on every viewport          SUCCESS
    FAIL      a required check failed: the build is what is wrong    FAILED, route `fail`,
              not retryable - the workflow routes it back to develop, whose next brief
              carries the failed checks and their frames
    BLOCKED   it could not be played here (no browser, the toolchain failed on a commit
              develop built): the environment, not the game          BLOCKED

The real checkout is never touched: the commit is cloned into the run's directory, so nothing
the bot does - a preview server, a build, test output - lands in the tree a reviewer
fingerprints or a developer commits. Every process goes through wgflib.procs; game code runs
with the allowlisted game environment (wgflib.agentenv), and the browser behind a proxy that
refuses every non-local request (wgflib.netguard). The frames stay beside the run as
evidence. This is automation evidence (`measurement_class: automation-bot`): it never stands
in for what first-time players understand.
"""

import copy
import datetime
import hashlib
import json
import os
import shutil
import socket

from wgflib import agentenv, checkout, paths, procs, provenance
from wgflib.netguard import RefusingProxy, sandbox_env
from wgflib.workflow import ArtifactOutput, StepResult, WorkflowStep
from wgflib.yamllite import load_file

from wgf_design.experience import load_rules as load_experience_rules

from . import analysis

__all__ = ["PlayabilityStep", "RULES_PATH", "BOT_SPEC", "FAIL_ROUTE"]

HERE = os.path.dirname(os.path.abspath(__file__))
BOT_SPEC = os.path.join(HERE, "bot.spec.ts")
RULES_PATH = os.path.join(paths.REFERENCE, "visual-quality.yaml")
FAIL_ROUTE = "fail"
REQUIRED_INPUTS = ("prototype-report", "game-design", "scaffold-record")
PROJECTS = (("desktop", 1280, 720), ("mobile", 393, 851))
_NO_BROWSER = ("Executable doesn't exist", "browserType.launch", "playwright install")

CONFIG = """\
// Generated by the Factory's playability step in a scratch clone. Serves the production
// build under dist/ with the repository's own `pnpm preview`.
import {{ defineConfig, devices }} from "@playwright/test";

const gl = ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"];

export default defineConfig({{
  testDir: "tests/wgf-play",
  outputDir: "test-results/wgf-play",
  workers: 1,
  retries: 0,
  timeout: 420_000,
  reporter: [["line"]],
  use: {{ baseURL: "http://localhost:{port}", launchOptions: {{ args: gl }} }},
  projects: [
    {{ name: "desktop", use: {{ ...devices["Desktop Chrome"], viewport: {{ width: 1280, height: 720 }} }} }},
    {{ name: "mobile", use: {{ ...devices["Pixel 5"] }} }},
  ],
  webServer: {{
    command: "pnpm preview --port {port} --strictPort",
    port: {port},
    reuseExistingServer: false,
    timeout: 120_000,
  }},
}});
"""


def _utc_now():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _free_port():
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]


def _sha256(path):
    with open(path, "rb") as handle:
        return "sha256:" + hashlib.sha256(handle.read()).hexdigest()


def load_rules(path=None):
    return load_file(path or RULES_PATH)


class PlayabilityStep(WorkflowStep):
    type = "playability"
    clock = staticmethod(_utc_now)

    def execute(self, inputs, context):
        missing = [t for t in REQUIRED_INPUTS if t not in inputs]
        if missing:
            return StepResult.waiting_for_input(
                f"playability needs {', '.join(missing)} in the run: there is no build to play")
        design = inputs.load("game-design")
        scaffold = inputs.load("scaffold-record")
        prototype = inputs.load("prototype-report")
        ex = (design.get("build_spec") or {}).get("experience")
        if not isinstance(ex, dict):
            return StepResult.blocked(
                "the game-design has no experience contract (build_spec.experience, game-design "
                "1.5.0): a build is played against it. Run design again.")
        commit = ((prototype.get("build_ref") or {}).get("commit_sha") or "").strip()
        if len(commit) != 40:
            return StepResult.failed("prototype-report names no built commit", retryable=False)
        title_id = scaffold.get("title_id") or prototype.get("title_id") or design.get("title_id")
        repository = scaffold.get("repository") or {}
        try:
            located, _source = checkout.locate(context.config, scaffold, "playability",
                                               self.params, name=repository.get("name") or title_id,
                                               logger=context.logger)
        except checkout.CheckoutError as exc:
            return StepResult.blocked(f"no game checkout to play: {exc}")
        if not os.path.isdir(os.path.join(located, ".git")):
            return StepResult.blocked(f"no game checkout at {located}")

        rules = load_rules()
        experience_rules = load_experience_rules()
        scratch = os.path.join(context.run_dir, "playability",
                               f"{getattr(context, 'visit', 1)}-{getattr(context, 'attempt', 1)}")
        shutil.rmtree(scratch, ignore_errors=True)
        os.makedirs(scratch)
        repo, out, logs = (os.path.join(scratch, d) for d in ("repo", "out", "logs"))
        os.makedirs(logs)
        try:
            blocked = self._prepare(located, commit, repo, logs, context)
            if blocked:
                return self._finish(context, inputs, title_id, commit, [], [], rules, blocked)
            idle_ms = max((experience_rules.get("onboarding") or {}).get("min_grace_s", 10),
                          (ex.get("onboarding") or {}).get("grace", {}).get("seconds") or 0) * 1000
            settings = {
                "idle_ms": int(idle_ms),
                "ack_ms": int(next((a.get("max_ack_ms") for a in ex.get("actions") or []), None)
                              or (experience_rules.get("feedback") or {}).get("max_ack_ms", 100)),
                "win_ms": int((rules.get("budgets") or {}).get("win_s", 180) * 1000),
                "lose_ms": int((rules.get("budgets") or {}).get("lose_s", 90) * 1000),
                "start_timeout_ms": 30000,
                "goal_metric": (ex.get("goal") or {}).get("metric"),
                "has_win": "win" in ex,
            }
            blocked = self._play(repo, out, logs, settings, context)
            judged = copy.deepcopy(rules)
            judged["_idle_ms"] = settings["idle_ms"]
            checks, frames, projects = [], [], []
            for project, width, height in PROJECTS:
                records = self._records(os.path.join(out, project))
                frames_dir = os.path.join(out, project, "frames")
                errors = sorted({e for r in records.values() for e in r.get("errors") or []})
                projects.append({"id": project, "viewport": {"width": width, "height": height},
                                 "ran": bool(records), "page_errors": errors[:10]})
                if records:
                    checks += analysis.judge(records, frames_dir, design, judged,
                                             experience_rules, project)
                frames += self._frames(frames_dir, project, context.run_dir)
            if not blocked and not any(p["ran"] for p in projects):
                blocked = "the bot produced no records on any viewport; see " + os.path.join(logs, "bot.log")
            return self._finish(context, inputs, title_id, commit, checks, frames, rules, blocked,
                                projects)
        finally:
            shutil.rmtree(repo, ignore_errors=True)

    # -- running ------------------------------------------------------------------------

    def _env(self, context):
        return agentenv.scrubbed(agentenv.game_passthrough(context.config))

    def _run(self, argv, cwd, timeout, log, env=None, context=None):
        result = procs.run(argv, cwd=cwd, timeout=timeout, env=env, log_path=log,
                           stderr_to_stdout=True)
        return result

    def _prepare(self, located, commit, repo, logs, context):
        """None when the commit is cloned, installed and built; else why it is blocked."""
        clone = self._run(["git", "clone", "--quiet", "--no-checkout", located, repo], None, 600,
                          os.path.join(logs, "clone.log"))
        if not clone.ok:
            return f"could not clone {located}: {clone.tail(5)}"
        switch = self._run(["git", "-C", repo, "checkout", "--quiet", "--detach", commit], None,
                           300, os.path.join(logs, "clone.log"))
        if not switch.ok:
            return f"commit {commit} is not in {located}"
        env = self._env(context)
        for argv, name in ((["pnpm", "install", "--frozen-lockfile", "--prefer-offline"], "install"),
                           (["pnpm", "build"], "build")):
            run = self._run(argv, repo, 1800, os.path.join(logs, f"{name}.log"), env=env)
            if not run.ok:
                return (f"`{' '.join(argv)}` failed on {commit[:12]}, which develop built: "
                        f"the environment, not the game ({os.path.join(logs, name + '.log')})")
        return None

    def _play(self, repo, out, logs, settings, context):
        """Run the bot. None when it ran (whatever it found); else why it could not."""
        port = _free_port()
        os.makedirs(os.path.join(repo, "tests", "wgf-play"), exist_ok=True)
        shutil.copy(BOT_SPEC, os.path.join(repo, "tests", "wgf-play", "bot.spec.ts"))
        with open(os.path.join(repo, "playwright.wgf-play.config.ts"), "w", encoding="utf-8") as h:
            h.write(CONFIG.format(port=port))
        config_path = os.path.join(out, "settings.json")
        os.makedirs(out, exist_ok=True)
        with open(config_path, "w", encoding="utf-8") as handle:
            json.dump(settings, handle)
        env = self._env(context)
        env.update(WGF_PLAY_OUT=out, WGF_PLAY_CONFIG=config_path)
        guard = RefusingProxy().start()
        env.update(sandbox_env(guard.url))
        try:
            run = self._run(["pnpm", "exec", "playwright", "test", "-c",
                             "playwright.wgf-play.config.ts"], repo, 2400,
                            os.path.join(logs, "bot.log"), env=env)
        finally:
            guard.stop()
        if not run.ok and any(marker in (run.output or "") for marker in _NO_BROWSER):
            return "no browser to play the build in here (playwright install chromium)"
        return None

    @staticmethod
    def _records(directory):
        records = {}
        for name in ("first-session", "act", "win", "lose"):
            path = os.path.join(directory, f"{name}.json")
            if os.path.isfile(path):
                with open(path, encoding="utf-8") as handle:
                    records[name] = json.load(handle)
        return records

    @staticmethod
    def _frames(frames_dir, project, run_dir):
        found = []
        if not os.path.isdir(frames_dir):
            return found
        for name in sorted(os.listdir(frames_dir)):
            if not name.endswith(".png"):
                continue
            path = os.path.join(frames_dir, name)
            entry = {"id": name[:-4], "project": project,
                     "path": os.path.relpath(path, run_dir).replace(os.sep, "/"),
                     "sha256": _sha256(path)}
            if not name.startswith("act-"):
                try:
                    (entry["mean_luminance"], entry["contrast"],
                     entry["lit_share"]) = analysis.frame_stats(path)
                except Exception:  # a frame that cannot be read is still listed  # noqa: BLE001
                    pass
            found.append(entry)
        return found

    # -- the report ---------------------------------------------------------------------

    def _finish(self, context, inputs, title_id, commit, checks, frames, rules, blocked,
                projects=None):
        failed = sorted({f"{c['project']}:{c['id']}" for c in checks
                         if c["required"] and c["status"] == "FAIL"})
        verdict = "BLOCKED" if blocked else ("FAIL" if failed else "PASS")
        now = self.clock()
        report = {
            "provenance": provenance.build(
                "playability-report",
                artifact_id=provenance.artifact_id("playability-report", title_id, now,
                                                   getattr(context, "execution", 1)),
                produced_by=provenance.producer("qa"), produced_at=now,
                inputs=provenance.pin_inputs(inputs, REQUIRED_INPUTS), title_id=title_id),
            "title_id": title_id,
            "commit": commit,
            "measurement_class": "automation-bot",
            "projects": projects or [{"id": p, "viewport": {"width": w, "height": h}, "ran": False}
                                     for p, w, h in PROJECTS],
            "checks": checks,
            "frames": frames,
            "failed_checks": failed,
            "blocked_reason": blocked,
            "verdict": verdict,
        }
        output = ArtifactOutput("playability-report", provenance.seal(report),
                                metadata={"verdict": verdict, "failed": len(failed),
                                          "commit": commit})
        if blocked:
            context.logger.warning("playability blocked", reason=blocked)
            return StepResult("BLOCKED", artifacts=[output], message=blocked)
        if failed:
            summaries = [f"{c['project']}:{c['id']}: {c['summary']}" for c in checks
                         if c["required"] and c["status"] == "FAIL"]
            context.logger.error("the build is not playable from outside", failed=failed)
            return StepResult("FAILED", route=FAIL_ROUTE, artifacts=[output], retryable=False,
                              error=f"{len(failed)} playability check(s) failed: "
                                    + "; ".join(summaries[:6]))
        return StepResult.success([output], message=(
            f"played {commit[:12]} on {', '.join(p['id'] for p in report['projects'] if p['ran'])}: "
            f"{len(checks)} checks passed"))
