"""The playability step: the build is played from outside before anyone calls it playable.

    prototype-report (commit) + game-design (experience contract) + scaffold-record
      -> clone that commit into scratch, install, build (the game repository's own pnpm)
      -> bot.spec.ts on desktop and mobile viewports, behind the refusing network proxy:
         four fresh first sessions - idle, act, win (oracle), lose and retry (anti-oracle)
      -> analysis.judge: the checks, against build_spec.experience and the bars
      -> playability-report

    PASS      every required check passed on every viewport          SUCCESS
    FAIL      a required check failed: the build is what is wrong    FAILED, route `fail`,
              not retryable - the workflow routes it back to develop, whose next brief
              carries the failed checks and their frames
    BLOCKED   it could not be played here (no browser, the toolchain failed on a commit
              develop built): the environment, not the game          BLOCKED

The real checkout is never touched: the commit is cloned into the run's directory, so nothing
the bot does - a preview server, a build, test output - lands in the tree a reviewer
fingerprints or a developer commits. Every process goes through wgflib.procs; game code runs
with the allowlisted game environment (wgflib.agentenv), and the browser behind a proxy that
refuses every non-local request (wgflib.netguard). The frames stay beside the run as
evidence. This is automation evidence (`measurement_class: automation-bot`): it never stands
in for what first-time players understand.
"""

import copy
import datetime
import hashlib
import json
import os
import shutil
import socket

from wgflib import agentenv, checkout, genre_models, paths, procs, provenance
from wgflib.netguard import BROWSER_BYPASS, BROWSER_PROXY_VAR, RefusingProxy, sandbox_env
from wgflib.workflow import ArtifactOutput, StepResult, WorkflowStep
from wgflib.yamllite import YamlError, load_file

from wgf_design.experience import load_rules as load_experience_rules

from . import analysis

__all__ = ["PlayabilityStep", "RULES_PATH", "BOT_SPEC", "FAIL_ROUTE", "RECORDS", "PROJECTS"]

HERE = os.path.dirname(os.path.abspath(__file__))
BOT_SPEC = os.path.join(HERE, "bot.spec.ts")
RULES_PATH = os.path.join(paths.REFERENCE, "visual-quality.yaml")
FAIL_ROUTE = "fail"
REQUIRED_INPUTS = ("prototype-report", "game-design", "scaffold-record")
# Seconds a session run plays past the bar it is judged on, so a session that ends on its own
# beat (a new best, a unit cleared) is seen rather than cut off at the bar.
SESSION_MARGIN_S = 45

PROJECTS = (("desktop", 1280, 720), ("mobile", 393, 851))
# The bot's records per viewport (bot.spec.ts): <out>/<project>/<name>.json.
RECORDS = ("first-session", "act", "win", "lose", "pause", "traverse", "persist", "session")
_NO_BROWSER = ("Executable doesn't exist", "browserType.launch", "playwright install")
# The control actions that leave a finished unit for the next one. A vocabulary, not a bar: the
# design's own control action ids naming one of these words are added to it.
ADVANCE_ACTIONS = ("next", "continue", "advance", "proceed", "next-level", "next-unit", "play")

CONFIG = """\
// Generated by the Factory's playability step in a scratch clone. Serves the production
// build under dist/ with the repository's own `pnpm preview`.
import {{ defineConfig, devices }} from "@playwright/test";

const gl = ["--use-gl=angle", "--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"];
// The Factory's refusing proxy, handed to the browser itself: Chromium ignores the proxy
// environment variables everywhere but Linux (wgflib.netguard).
const server = process.env["{proxy_var}"];
const proxy = server ? {{ proxy: {{ server, bypass: "{bypass}" }} }} : {{}};

export default defineConfig({{
  testDir: "tests/wgf-play",
  outputDir: "test-results/wgf-play",
  workers: 1,
  retries: 0,
  timeout: 420_000,
  reporter: [["line"]],
  use: {{ baseURL: "http://localhost:{port}", launchOptions: {{ args: gl }}, ...proxy }},
  projects: [
    {{ name: "desktop", use: {{ ...devices["Desktop Chrome"], viewport: {{ width: 1280, height: 720 }} }} }},
    {{ name: "mobile", use: {{ ...devices["Pixel 5"] }} }},
  ],
  webServer: {{
    command: "pnpm preview --port {port} --strictPort",
    port: {port},
    reuseExistingServer: false,
    timeout: 120_000,
  }},
}});
"""


def _utc_now():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _free_port():
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]


def _sha256(path):
    with open(path, "rb") as handle:
        return "sha256:" + hashlib.sha256(handle.read()).hexdigest()


def load_rules(path=None):
    return load_file(path or RULES_PATH)


class PlayabilityStep(WorkflowStep):
    type = "playability"
    clock = staticmethod(_utc_now)

    def execute(self, inputs, context):
        missing = [t for t in REQUIRED_INPUTS if t not in inputs]
        if missing:
            return StepResult.waiting_for_input(
                f"playability needs {', '.join(missing)} in the run: there is no build to play")
        design = inputs.load("game-design")
        scaffold = inputs.load("scaffold-record")
        prototype = inputs.load("prototype-report")
        ex = (design.get("build_spec") or {}).get("experience")
        if not isinstance(ex, dict):
            return StepResult.blocked(
                "the game-design has no experience contract (build_spec.experience, game-design "
                "1.5.0): a build is played against it. Run design again.")
        commit = ((prototype.get("build_ref") or {}).get("commit_sha") or "").strip()
        if len(commit) != 40:
            return StepResult.failed("prototype-report names no built commit", retryable=False)
        title_id = scaffold.get("title_id") or prototype.get("title_id") or design.get("title_id")
        repository = scaffold.get("repository") or {}
        try:
            located, _source = checkout.locate(context.config, scaffold, "playability",
                                               self.params, name=repository.get("name") or title_id,
                                               logger=context.logger)
        except checkout.CheckoutError as exc:
            return StepResult.blocked(f"no game checkout to play: {exc}")
        if not os.path.isdir(os.path.join(located, ".git")):
            return StepResult.blocked(f"no game checkout at {located}")

        rules = load_rules()
        experience_rules = load_experience_rules()
        try:
            # The bars the content, difficulty and depth checks read: design-depth.yaml's
            # `playability` block with the genre family's `qa` overrides.
            qa = genre_models.qa_of(design)
        except (OSError, YamlError, ValueError) as exc:
            return StepResult.blocked(
                f"the genre model and depth bars could not be read ({exc}): nothing can be held "
                "to them, and no bar is defaulted in code")
        # Keyed by step: a workflow plays more than one build (greybox-playability,
        # playability), each step's visits count from 1, and this directory is emptied
        # first - one shared directory erased the greybox's frames its report cites.
        scratch = os.path.join(context.run_dir,
                               getattr(context, "current_step", None) or "playability",
                               f"{getattr(context, 'visit', 1)}-{getattr(context, 'attempt', 1)}")
        shutil.rmtree(scratch, ignore_errors=True)
        os.makedirs(scratch)
        repo, out, logs = (os.path.join(scratch, d) for d in ("repo", "out", "logs"))
        os.makedirs(logs)
        try:
            blocked = self._prepare(located, commit, repo, logs, context)
            if blocked:
                return self._finish(context, inputs, title_id, commit, [], [], rules, blocked)
            idle_ms = max((experience_rules.get("onboarding") or {}).get("min_grace_s", 10),
                          (ex.get("onboarding") or {}).get("grace", {}).get("seconds") or 0) * 1000
            settings = {
                "idle_ms": int(idle_ms),
                "ack_ms": int(next((a.get("max_ack_ms") for a in ex.get("actions") or []), None)
                              or (experience_rules.get("feedback") or {}).get("max_ack_ms", 100)),
                "win_ms": int((rules.get("budgets") or {}).get("win_s", 180) * 1000),
                "lose_ms": int((rules.get("budgets") or {}).get("lose_s", 90) * 1000),
                "start_timeout_ms": 30000,
                "goal_metric": (ex.get("goal") or {}).get("metric"),
                "has_win": "win" in ex,
            }
            content_settings, truncated, total_s = self._content_settings(design, qa, settings)
            settings.update(content_settings)
            blocked = self._play(repo, out, logs, settings, context, total_s)
            judged = copy.deepcopy(rules)
            judged["_idle_ms"] = settings["idle_ms"]
            judged["_truncated"] = truncated
            checks, frames, projects = [], [], []
            for project, width, height in PROJECTS:
                records = self._records(os.path.join(out, project))
                frames_dir = os.path.join(out, project, "frames")
                errors = sorted({e for r in records.values() for e in r.get("errors") or []})
                projects.append({"id": project, "viewport": {"width": width, "height": height},
                                 "ran": bool(records), "page_errors": errors[:10]})
                if records:
                    checks += analysis.judge(records, frames_dir, design, judged,
                                             experience_rules, project, qa=qa)
                frames += self._frames(frames_dir, project, context.run_dir)
            if not blocked and not any(p["ran"] for p in projects):
                blocked = "the bot produced no records on any viewport; see " + os.path.join(logs, "bot.log")
            records_dir = (os.path.relpath(out, context.run_dir).replace(os.sep, "/")
                           if os.path.isdir(out) else None)
            return self._finish(context, inputs, title_id, commit, checks, frames, rules, blocked,
                                projects, records_dir)
        finally:
            shutil.rmtree(repo, ignore_errors=True)

    # -- what the bot is given ----------------------------------------------------------

    @staticmethod
    def _content_settings(design, qa, settings):
        """(the CFG the content, persist and session tests read, which of them were cut, the
        viewport's whole time budget in seconds).

        The time budget (design-depth.yaml `playability.time_budget.bot_total_s`) is a hard cap
        per viewport. What the first-session, act, win, lose and pause tests already cost is
        subtracted; whatever is left is shared out between the traverse, persist and session
        windows in proportion to what they asked for, and every check judged from a window that
        was cut is marked `truncated`.
        """
        spec = (design or {}).get("build_spec") or {}
        content, _mode, units = analysis.content_units(design)
        depth = spec.get("depth") or {}
        budget = qa.get("time_budget") or {}
        bars = qa.get("content") or {}
        session_bars = qa.get("session_length") or {}
        genre = qa.get("genre") or {}
        target_s = ((depth.get("first_session") or {}).get("target_s") or 0)
        content_applies = content is not None
        depth_applies = bool(depth.get("meta_loop") or depth.get("first_session"))
        asked = {
            "traverse": (budget.get("traverse_s") or 0) * 1000 if content_applies else 0,
            "persist": (budget.get("persist_s") or 0) * 1000 if depth_applies else 0,
            # Never play longer than the bar needs: the check passes at
            # `min_share` x target, so a window of that plus a margin measures everything a
            # `max_multiplier` window would, and the run (and every measurement after it on
            # the same machine) is minutes shorter.
            "session": (min(target_s * (session_bars.get("max_multiplier") or 0),
                            target_s * (session_bars.get("min_share") or 0) + SESSION_MARGIN_S)
                        * 1000 if depth_applies else 0),
        }
        total_s = budget.get("bot_total_s") or 0
        spent = (settings["idle_ms"] + settings["win_ms"] + settings["lose_ms"]
                 + 2 * settings["start_timeout_ms"])
        room = max(0, total_s * 1000 - spent)
        wanted = sum(asked.values())
        scale = min(1.0, room / wanted) if wanted else 1.0
        truncated = {name: bool(ms and scale < 1.0) for name, ms in asked.items()}
        want_units = min(len(units), int(bars.get("min_units_traversed") or 1)) if units else 0
        actions = [a.get("id") for a in ((spec.get("controls") or {}).get("actions") or [])
                   if isinstance(a, dict) and isinstance(a.get("id"), str)
                   and any(word in a["id"].lower() for word in ADVANCE_ACTIONS)]
        session_ms = int(asked["session"] * scale)
        return {
            "content_applies": content_applies,
            "depth_applies": depth_applies,
            "unit_count": len(units),
            "max_units": want_units + 1,
            "traverse_ms": int(asked["traverse"] * scale),
            "persist_ms": int(asked["persist"] * scale),
            "session_target_ms": int(target_s * 1000),
            "session_max_ms": session_ms,
            "window_ms": int(((qa.get("difficulty") or {}).get("endless_window_s") or 0) * 1000),
            "axes": [a["id"] for a in genre_models.axes_of(design)],
            "advance_actions": sorted(set(actions) | set(ADVANCE_ACTIONS)),
            "reset_in_unit": bool(genre.get("reset_in_unit")),
        }, truncated, total_s

    # -- running ------------------------------------------------------------------------

    def _env(self, context):
        return agentenv.scrubbed(agentenv.game_passthrough(context.config))

    def _run(self, argv, cwd, timeout, log, env=None, context=None):
        result = procs.run(argv, cwd=cwd, timeout=timeout, env=env, log_path=log,
                           stderr_to_stdout=True)
        return result

    def _prepare(self, located, commit, repo, logs, context):
        """None when the commit is cloned, installed and built; else why it is blocked."""
        clone = self._run(["git", "clone", "--quiet", "--no-checkout", located, repo], None, 600,
                          os.path.join(logs, "clone.log"))
        if not clone.ok:
            return f"could not clone {located}: {clone.tail(5)}"
        switch = self._run(["git", "-C", repo, "checkout", "--quiet", "--detach", commit], None,
                           300, os.path.join(logs, "clone.log"))
        if not switch.ok:
            return f"commit {commit} is not in {located}"
        env = self._env(context)
        for argv, name in ((["pnpm", "install", "--frozen-lockfile", "--prefer-offline"], "install"),
                           (["pnpm", "build"], "build")):
            run = self._run(argv, repo, 1800, os.path.join(logs, f"{name}.log"), env=env)
            if not run.ok:
                return (f"`{' '.join(argv)}` failed on {commit[:12]}, which develop built: "
                        f"the environment, not the game ({os.path.join(logs, name + '.log')})")
        return None

    def _play(self, repo, out, logs, settings, context, bot_total_s=0):
        """Run the bot. None when it ran (whatever it found); else why it could not."""
        port = _free_port()
        os.makedirs(os.path.join(repo, "tests", "wgf-play"), exist_ok=True)
        shutil.copy(BOT_SPEC, os.path.join(repo, "tests", "wgf-play", "bot.spec.ts"))
        with open(os.path.join(repo, "playwright.wgf-play.config.ts"), "w", encoding="utf-8") as h:
            h.write(CONFIG.format(port=port, proxy_var=BROWSER_PROXY_VAR, bypass=BROWSER_BYPASS))
        config_path = os.path.join(out, "settings.json")
        os.makedirs(out, exist_ok=True)
        with open(config_path, "w", encoding="utf-8") as handle:
            json.dump(settings, handle)
        env = self._env(context)
        env.update(WGF_PLAY_OUT=out, WGF_PLAY_CONFIG=config_path)
        guard = RefusingProxy().start()
        env.update(sandbox_env(guard.url))
        # The bot's own budget decides the timeout, not a fixed number: two viewports of
        # bot_total_s, plus the install-free start-up and the report.
        timeout = int(2 * (bot_total_s or 0) + 120) or 2400
        try:
            run = self._run(["pnpm", "exec", "playwright", "test", "-c",
                             "playwright.wgf-play.config.ts"], repo, timeout,
                            os.path.join(logs, "bot.log"), env=env)
        finally:
            guard.stop()
        if not run.ok and any(marker in (run.output or "") for marker in _NO_BROWSER):
            return "no browser to play the build in here (playwright install chromium)"
        return None

    @staticmethod
    def _records(directory):
        records = {}
        for name in RECORDS:
            path = os.path.join(directory, f"{name}.json")
            if os.path.isfile(path):
                with open(path, encoding="utf-8") as handle:
                    records[name] = json.load(handle)
        return records

    @staticmethod
    def _frames(frames_dir, project, run_dir):
        found = []
        if not os.path.isdir(frames_dir):
            return found
        for name in sorted(os.listdir(frames_dir)):
            if not name.endswith(".png"):
                continue
            path = os.path.join(frames_dir, name)
            entry = {"id": name[:-4], "project": project,
                     "path": os.path.relpath(path, run_dir).replace(os.sep, "/"),
                     "sha256": _sha256(path)}
            if not name.startswith("act-"):
                try:
                    (entry["mean_luminance"], entry["contrast"],
                     entry["lit_share"]) = analysis.frame_stats(path)
                except Exception:  # a frame that cannot be read is still listed  # noqa: BLE001
                    pass
            found.append(entry)
        return found

    # -- the report ---------------------------------------------------------------------

    def _finish(self, context, inputs, title_id, commit, checks, frames, rules, blocked,
                projects=None, records_dir=None):
        failed = sorted({f"{c['project']}:{c['id']}" for c in checks
                         if c["required"] and c["status"] == "FAIL"})
        # A skipped check measured nothing, because the design claims nothing it could measure.
        # Listed once per id with its reason: a reader counting passes subtracts these.
        skipped = []
        for check in checks:
            if check["status"] == "SKIPPED" and check["id"] not in {s["id"] for s in skipped}:
                skipped.append({"id": check["id"], "reason": check["summary"]})
        verdict = "BLOCKED" if blocked else ("FAIL" if failed else "PASS")
        now = self.clock()
        report = {
            "provenance": provenance.build(
                "playability-report",
                artifact_id=provenance.artifact_id("playability-report", title_id, now,
                                                   getattr(context, "execution", 1)),
                produced_by=provenance.producer("qa"), produced_at=now,
                inputs=provenance.pin_inputs(inputs, REQUIRED_INPUTS), title_id=title_id),
            "title_id": title_id,
            "commit": commit,
            "measurement_class": "automation-bot",
            "projects": projects or [{"id": p, "viewport": {"width": w, "height": h}, "ran": False}
                                     for p, w, h in PROJECTS],
            "checks": checks,
            "frames": frames,
            "records_dir": records_dir,
            "failed_checks": failed,
            "skipped_checks": skipped,
            "blocked_reason": blocked,
            "verdict": verdict,
        }
        output = ArtifactOutput("playability-report", provenance.seal(report),
                                metadata={"verdict": verdict, "failed": len(failed),
                                          "skipped": len(skipped), "commit": commit})
        if blocked:
            context.logger.warning("playability blocked", reason=blocked)
            return StepResult("BLOCKED", artifacts=[output], message=blocked)
        if failed:
            summaries = [f"{c['project']}:{c['id']}: {c['summary']}" for c in checks
                         if c["required"] and c["status"] == "FAIL"]
            context.logger.error("the build is not playable from outside", failed=failed)
            return StepResult("FAILED", route=FAIL_ROUTE, artifacts=[output], retryable=False,
                              error=f"{len(failed)} playability check(s) failed: "
                                    + "; ".join(summaries[:6]) + self._skipped_note(skipped))
        return StepResult.success([output], message=(
            f"played {commit[:12]} on {', '.join(p['id'] for p in report['projects'] if p['ran'])}: "
            f"{sum(1 for c in checks if c['status'] == 'PASS')} checks passed"
            + self._skipped_note(skipped)))

    @staticmethod
    def _skipped_note(skipped):
        """A skip is never a pass: the summary names every one of them."""
        if not skipped:
            return ""
        return (f". {len(skipped)} check(s) measured nothing, because the design claims nothing "
                "they measure (not passes): " + ", ".join(s["id"] for s in skipped))
