"""The side effect: what the step writes into the game repository, and what it finds there.

Three kinds of change, all convergent - running the step twice leaves the repository as
running it once did, which is this module's idempotency (docs/workflow-module-contract.md
§8). Nothing is committed or pushed; the game repository's own history is its owner's.

1. Files the step owns outright, copied from `game/` beside this file:
       src/platform/gameplay.ts                     the gameplay integration layer
       tests/unit/platform/gameplay-integration.test.ts   its SDK-mock suite
   and one it generates, src/platform/integration-plan.ts, from the game-design.
2. One patch to src/main.ts, the template's boot sequence: boot through `bootPlatform`
   (runtime SDK failure degrades instead of blanking the screen), and install the
   `PlatformGameplay` instance scenes call. Applied only when the template's own lines are
   found exactly; otherwise main.ts is left alone and the boot hook reported unwired.
3. Nothing else. Gameplay code - where the player dies, where a level ends - belongs to the
   develop step. This module reads it (`scan_hooks`) to report which moments are wired.
"""

import json
import os
import re

__all__ = [
    "OWNED_FILES",
    "SEAM_FILES",
    "has_seam",
    "write_seam_files",
    "patch_seam",
    "scan_seam",
    "PLAN_FILE",
    "MAIN_FILE",
    "write_owned_files",
    "write_plan",
    "patch_main",
    "scan_hooks",
    "render_plan",
]

HERE = os.path.dirname(os.path.abspath(__file__))
GAME_FILES = os.path.join(HERE, "game")

OWNED_FILES = (
    "src/platform/gameplay.ts",
    "tests/unit/platform/gameplay-integration.test.ts",
)
# Written only when the game declares the develop step's seam, src/game/integration.ts.
SEAM_FILES = (
    "src/platform/game-integration.ts",
    "tests/unit/platform/game-integration.test.ts",
)
SEAM_DECLARATION = "src/game/integration.ts"
PLAN_FILE = "src/platform/integration-plan.ts"
MAIN_FILE = "src/main.ts"
PRINT_WIDTH = 100


def _write_if_changed(repo, relative, text):
    """'created', 'updated' or 'unchanged'. Never rewrites identical content."""
    path = os.path.join(repo, *relative.split("/"))
    before = None
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            before = handle.read()
    if before == text:
        return "unchanged"
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    return "created" if before is None else "updated"


def has_seam(repo):
    path = os.path.join(repo, *SEAM_DECLARATION.split("/"))
    if not os.path.exists(path):
        return False
    with open(path, encoding="utf-8") as handle:
        return "interface GameIntegration" in handle.read()


def write_seam_files(repo):
    return write_owned_files(repo, SEAM_FILES)


def write_owned_files(repo, files=OWNED_FILES):
    records = []
    for relative in files:
        with open(os.path.join(GAME_FILES, *relative.split("/")), encoding="utf-8") as handle:
            text = handle.read()
        records.append({"path": relative, "action": _write_if_changed(repo, relative, text)})
    return records


# -- the generated plan ---------------------------------------------------------------------

_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _ts(value, indent):
    """`value` as a TypeScript literal in the template's prettier style."""
    pad, inner = "  " * indent, "  " * (indent + 1)
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = []
        for key, item in value.items():
            name = key if _IDENTIFIER.match(key) else json.dumps(key)
            lines.append(f"{inner}{name}: {_ts(item, indent + 1)},")
        return "{\n" + "\n".join(lines) + f"\n{pad}}}"
    if isinstance(value, list):
        if not value:
            return "[]"
        flat = "[" + ", ".join(_ts(item, indent + 1) for item in value) + "]"
        if "\n" not in flat and len(inner) + len(flat) + 30 <= PRINT_WIDTH:
            return flat
        return "[\n" + "\n".join(f"{inner}{_ts(i, indent + 1)}," for i in value) + f"\n{pad}]"
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(value, ensure_ascii=False)


def render_plan(plan, source):
    return (
        f"// Generated by the Factory's `sdk` workflow step from {source}.\n"
        "// Do not edit: change the game-design and run the step again.\n"
        "\n"
        'import type { IntegrationPlan } from "./gameplay.js";\n'
        "\n"
        f"export const INTEGRATION_PLAN: IntegrationPlan = {_ts(plan, 0)};\n"
    )


def write_plan(repo, plan, source):
    action = _write_if_changed(repo, PLAN_FILE, render_plan(plan, source))
    return {"path": PLAN_FILE, "action": action}


# -- main.ts --------------------------------------------------------------------------------

_IMPORT_CREATE = re.compile(r'^import \{ createPlatform \} from "@wgf/platform-sdk";\n', re.M)
_BOOT = re.compile(
    r"^(?P<i>[ \t]*)const platform = createPlatform\((?P<id>[^,\n]+), \{ namespace: "
    r"(?P<ns>[^}\n]+?) \}\);\n(?P=i)await platform\.initialize\(\);\n",
    re.M,
)
_NEW_GAME = re.compile(r"^(?P<i>[ \t]*)const game = new Game\(\);\n", re.M)
_START = re.compile(r"^(?P<i>[ \t]*)game\.start\(\);\n(?P=i)platform\.gameplayStart\(\);\n", re.M)


def patch_main(repo):
    """Route the template's boot through the integration. Returns a file record."""
    path = os.path.join(repo, *MAIN_FILE.split("/"))
    if not os.path.exists(path):
        return {"path": MAIN_FILE, "action": "skipped", "note": "no src/main.ts"}
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    if "bootPlatform(" in text:
        return {"path": MAIN_FILE, "action": "unchanged"}

    anchors = {"import": _IMPORT_CREATE.search(text), "boot": _BOOT.search(text),
               "game": _NEW_GAME.search(text)}
    missing = [name for name, match in anchors.items() if match is None]
    # Optional: a template that starts gameplay at boot hands that to runStarted. One that
    # waits for the player's first input (Poki asks for that) leaves it to the game.
    starts_at_boot = _START.search(text) is not None
    if missing:
        return {"path": MAIN_FILE, "action": "skipped",
                "note": "the template's boot sequence was not found unchanged (no match for: "
                        + ", ".join(missing) + "); wire bootPlatform and PlatformGameplay "
                        "by hand as src/platform/gameplay.ts describes"}

    boot = anchors["boot"]
    i = boot.group("i")
    text = _BOOT.sub(
        lambda m: (
            f"{i}const booted = await bootPlatform({m.group('id')}, {{\n"
            f"{i}  namespace: {m.group('ns')},\n"
            f"{i}  plan: INTEGRATION_PLAN,\n"
            f"{i}}});\n"
            f"{i}const platform = booted.platform;\n"
            f"{i}// The adapter's initialize() rejected: play on without it rather than show\n"
            f"{i}// a blank page, and leave the reason where the verify suite can see it.\n"
            f"{i}if (booted.degraded) console.warn(\"platform degraded\", booted.degraded);\n"
        ),
        text, count=1)
    text = _NEW_GAME.sub(
        lambda m: (
            f"{m.group('i')}const game = new Game();\n"
            + (f"{m.group('i')}const gameplay = installGameplay(\n"
               f"{m.group('i')}  new PlatformGameplay(game, platform, INTEGRATION_PLAN, "
               f"{{ target: booted.target }}),\n"
               f"{m.group('i')});\n"
               if starts_at_boot else
               f"{m.group('i')}installGameplay(\n"
               f"{m.group('i')}  new PlatformGameplay(game, platform, INTEGRATION_PLAN, "
               f"{{ target: booted.target }}),\n"
               f"{m.group('i')});\n")
        ),
        text, count=1)
    if starts_at_boot:
        text = _START.sub(
            lambda m: f"{m.group('i')}game.start();\n{m.group('i')}gameplay.runStarted();\n",
            text, count=1)
    imports = (
        'import { bootPlatform, installGameplay, PlatformGameplay } from '
        '"./platform/gameplay.js";\n'
        'import { INTEGRATION_PLAN } from "./platform/integration-plan.js";\n'
    )
    if "createPlatform" in _IMPORT_CREATE.sub("", text):
        text = text.replace(anchors["import"].group(0), anchors["import"].group(0) + imports, 1)
    else:
        text = _IMPORT_CREATE.sub(lambda m: imports, text, count=1)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    return {"path": MAIN_FILE, "action": "patched"}


# -- reading the game -----------------------------------------------------------------------

# Method names specific enough to recognise on any receiver - scenes hold the instance under
# whatever name they like. The generic ones (save, load, pause, resume) count only in files
# that import the gameplay module, where they can be ours.
_DISTINCT_CALL = re.compile(
    r"\.\s*(runStarted|continueFrom|gameOver|levelComplete|canOfferReward|offerReward|"
    r"naturalBreak)\s*"
    r"\(\s*(?:\"([a-z-]+)\")?"
)
_GENERIC_CALL = re.compile(r"\.\s*(save|load|pause|resume)\s*(?:<[^>]*>)?\(")
_IMPORTS_GAMEPLAY = re.compile(r'from\s+"[./]*(?:platform/)?gameplay\.js"')
_MAIN_CALLS = {
    "boot": re.compile(r"\bbootPlatform\s*\("),
    "loading-progress": re.compile(r"\.reportLoadingProgress\s*\("),
    "game-ready": re.compile(r"\.signalReady\s*\("),
    "platform-binding": re.compile(r"(?<!function )\bbindPlatform\s*\("),
    "audio-mute": re.compile(r"\bonAudioMutedChange\b"),
    "tracker": re.compile(r"\bnew PlatformGameplay\s*\([^;]*\btracker\s*:", re.S),
    "gameplay-audio": re.compile(r"\bnew PlatformGameplay\s*\([^;]*\baudio\s*:", re.S),
}
_HOOK_NAMES = {
    "runStarted": "run-start",
    "continueFrom": "continue-from",
    "gameOver": "game-over",
    "levelComplete": "level-complete",
    "pause": "pause",
    "resume": "resume",
    "canOfferReward": "can-offer-reward",
    "offerReward": "offer-reward",
    "naturalBreak": "natural-break",
    "save": "save",
    "load": "load",
}


def _source_files(repo):
    root = os.path.join(repo, "src")
    skip = {os.path.normpath(os.path.join(repo, *p.split("/")))
            for p in (*OWNED_FILES, *SEAM_FILES, PLAN_FILE)}
    for directory, dirs, files in os.walk(root):
        dirs.sort()
        for name in sorted(files):
            path = os.path.normpath(os.path.join(directory, name))
            if name.endswith(".ts") and not name.endswith(".d.ts") and path not in skip:
                yield path


def scan_hooks(repo):
    """hook name -> ['src/file.ts:line', ...] for every hook the game source calls.

    Hooks with a moment carry it: `offer-reward:game-over`, `natural-break:level-complete`.
    """
    found = {}
    for path in _source_files(repo):
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
        relative = os.path.relpath(path, repo).replace(os.sep, "/")

        def add(hook, offset):
            line = text.count("\n", 0, offset) + 1
            found.setdefault(hook, []).append(f"{relative}:{line}")

        for match in _DISTINCT_CALL.finditer(text):
            hook = _HOOK_NAMES[match.group(1)]
            add(hook, match.start())
            if match.group(2):
                add(f"{hook}:{match.group(2)}", match.start())
        if _IMPORTS_GAMEPLAY.search(text):
            for match in _GENERIC_CALL.finditer(text):
                add(_HOOK_NAMES[match.group(1)], match.start())
        for hook, pattern in _MAIN_CALLS.items():
            for match in pattern.finditer(text):
                add(hook, match.start())
    return found


# -- the develop step's seam ----------------------------------------------------------------

_SEAM_PLACEMENT = re.compile(r"\.\s*(canOfferRewarded|rewarded|interstitial)\s*\(\s*\"([^\"]+)\"")
_SEAM_GAMEPLAY = re.compile(r"\.\s*(gameplayStart|gameplayStop)\s*\(")
_SEAM_STORAGE = re.compile(r"\.\s*(save|load)\s*\(")
_IMPORTS_SEAM = re.compile(r'from\s+"[./]*(?:game/)?integration\.js"')


def scan_seam(repo):
    """What the game calls on its seam, outside src/platform/ (where the wiring lives).

    Returns {"placements": {kind: {id: [file:line]}}, "calls": {name: [file:line]}}, kind
    being "rewarded" (from canOfferRewarded or rewarded) or "interstitial".
    """
    placements = {"rewarded": {}, "interstitial": {}}
    calls = {}
    declaration = os.path.normpath(os.path.join(repo, *SEAM_DECLARATION.split("/")))
    for path in _source_files(repo):
        relative = os.path.relpath(path, repo).replace(os.sep, "/")
        if path == declaration or relative.startswith("src/platform/"):
            continue
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
        if not _IMPORTS_SEAM.search(text) and "GameIntegration" not in text:
            continue

        def where(offset):
            return f"{relative}:{text.count(chr(10), 0, offset) + 1}"

        for match in _SEAM_PLACEMENT.finditer(text):
            kind = "interstitial" if match.group(1) == "interstitial" else "rewarded"
            placements[kind].setdefault(match.group(2), []).append(where(match.start()))
            calls.setdefault(match.group(1), []).append(where(match.start()))
        for pattern in (_SEAM_GAMEPLAY, _SEAM_STORAGE):
            for match in pattern.finditer(text):
                calls.setdefault(match.group(1), []).append(where(match.start()))
    return {"placements": placements, "calls": calls}


_DEFAULT_CLASS = re.compile(r"export\s+class\s+(\w+)\s+implements\s+[^{]*\bGameIntegration\b")
_DEFAULT_FACTORY = re.compile(
    r"export\s+(?:async\s+)?function\s+(\w+)\s*\([^)]*\)\s*:\s*GameIntegration\b")
_SEAM_IMPORT = ('import { PlatformGameIntegration } from "./platform/game-integration.js";\n')


def _call_span(text, start):
    """End offset of the balanced call whose '(' is at or after `start`."""
    depth, i = 0, text.index("(", start)
    while i < len(text):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return None


def patch_seam(repo):
    """Swap the develop step's default seam implementation in main.ts for the platform's."""
    path = os.path.join(repo, *MAIN_FILE.split("/"))
    record = {"path": MAIN_FILE + " (seam)", "action": "skipped"}
    if not os.path.exists(path):
        return dict(record, note="no src/main.ts")
    with open(path, encoding="utf-8") as handle:
        text = handle.read()
    if "PlatformGameIntegration" in text:
        return dict(record, action="unchanged")

    default = None
    platform_dir = os.path.join(repo, "src", "platform")
    for name in sorted(os.listdir(platform_dir)) if os.path.isdir(platform_dir) else []:
        if not name.endswith(".ts") or f"src/platform/{name}" in (*OWNED_FILES, *SEAM_FILES,
                                                                   PLAN_FILE):
            continue
        with open(os.path.join(platform_dir, name), encoding="utf-8") as handle:
            source = handle.read()
        found = _DEFAULT_CLASS.search(source) or _DEFAULT_FACTORY.search(source)
        if found:
            default = (found.group(1), found.re is _DEFAULT_CLASS)
            break
    if default is None:
        return dict(record, note="no default GameIntegration implementation under "
                                 "src/platform/ to replace; construct PlatformGameIntegration "
                                 "in main.ts by hand")
    name, is_class = default
    construction = re.search((r"\bnew\s+" if is_class else r"(?<![\w.])") + re.escape(name)
                             + r"\s*\(", text)
    if construction is None:
        return dict(record, note=f"main.ts does not construct {name}; construct "
                                 f"PlatformGameIntegration where the game gets its seam")
    end = _call_span(text, construction.start())
    text = text[:construction.start()] + "new PlatformGameIntegration()" + text[end:]
    # The default's import goes if nothing else uses it; the platform's comes in.
    if not re.search(r"\b" + re.escape(name) + r"\b",
                     re.sub(r"^import [^;]*;\n", "", text, flags=re.M)):
        text = re.sub(r"^import \{([^}]*)\} from ([^;]*);\n",
                      lambda m: _drop_specifier(m, name), text, flags=re.M)
    last_import = list(re.finditer(r"^import [^;]*;\n", text, re.M))[-1]
    text = text[:last_import.end()] + _SEAM_IMPORT + text[last_import.end():]
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    return dict(record, action="patched", note=f"{name} replaced by PlatformGameIntegration")


def _drop_specifier(match, name):
    specifiers = [s.strip() for s in match.group(1).split(",") if s.strip()]
    kept = [s for s in specifiers if re.sub(r"^type\s+", "", s).split(" as ")[-1] != name]
    if len(kept) == len(specifiers):
        return match.group(0)
    if not kept:
        return ""
    return "import { " + ", ".join(kept) + " } from " + match.group(2) + ";\n"
