"""Browser QA: the built game in a real browser at every viewport a player brings.

    core/reference/browser-qa.yaml (viewports, checks, tiers, bars)
      -> browser_qa.spec.ts copied into the checkout's git-ignored build/wgf-browser-qa/,
         run with the repository's own Playwright against `pnpm preview` of the build,
         one project per viewport, behind the refusing network proxy
      -> records per viewport (viewport, outcomes, perf, clips)       [measure]
      -> judge(): every check of the contract, as Check objects        [decide]

The spec records and never judges; `judge` holds the records to the contract's bars, so the
judging is tested offline from recorded fixtures (scripts/tests/test_browser_qa.py) and the
same records always give the same checks.

Tiers (browser-qa.yaml): `hard` checks are required at every quality tier; `quality` checks
are required where the run's quality-tier class is in `quality_required_at` (the release
class, as shipped) and are WARNINGs elsewhere; `advisory` checks are never required. A check
that measured nothing is never a PASS: BLOCKED where it is required and the measurement was
possible (the spec did not run, the host was degraded on every attempt), a WARNING where the
game has nothing of that kind to measure (no pause control, no mute control). A check the
build could have been measured on but whose data it OMITS - the play probe reports no
gameplay-critical entity, or no audio level; the bundle ships no runtime manifest - is held
as core/reference/quality-policy.yaml `skipped_checks` says (wgflib.check_strength): at a tier
whose class is under `not_passed_at` (release) it is BLOCKED and required, never a note the
quality floor could pass over; elsewhere a WARNING.

Timing checks re-use the playability bot's host-health judgement
(wgf_playability.analysis.environment_health, with visual-quality.yaml `environment`): a
recording whose last attempt was degraded is BLOCKED, never passed and never failed.
"""

import json
import math
import os
import re
import shutil
import socket
import statistics
import struct

from wgflib import check_strength, paths
from wgflib.netguard import BROWSER_BYPASS, BROWSER_PROXY_VAR
from wgflib.workflow import references as pinned_references
from wgflib.workflow.quality import run_tier
from wgflib.yamllite import load as load_yaml
from wgflib.yamllite import load_file

from .model import BLOCKED, FAIL, PASS, WARNING, Check, Evidence

__all__ = ["CONTRACT_PATH", "SPEC", "WORK_DIR", "load_contract", "settings", "check_browser",
           "judge", "required_for", "scan_bundle", "RUN_CHECK"]

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC = os.path.join(HERE, "browser_qa.spec.ts")
CONTRACT_PATH = os.path.join(paths.REFERENCE, "browser-qa.yaml")
QUALITY_POLICY = os.path.join(paths.REFERENCE, "quality-policy.yaml")
# Inside the checkout, under the template's git-ignored /build/: the spec, its config, the
# records. Nothing is committed and the tree stays clean.
WORK_DIR = "build/wgf-browser-qa"
RUN_CHECK = "browser.run"
_NO_BROWSER = ("Executable doesn't exist", "browserType.launch", "playwright install")
IMAGE_EXT = (".png", ".jpg", ".jpeg", ".webp", ".gif", ".ktx2", ".basis", ".avif")
AUDIO_EXT = (".ogg", ".mp3", ".wav", ".m4a", ".aac", ".opus", ".webm", ".flac")

CONFIG = """\
// Generated by the Factory's verify step (browser QA). Serves the production build under
// dist/ with the repository's own `pnpm preview`; one project per viewport.
import {{ defineConfig }} from "@playwright/test";

// The host's GPU where there is one: frame times on a software rasterizer measure the host,
// not the game (browser-qa.yaml `software_renderers`). With no GPU, Chromium falls back to
// SwiftShader, and a frame-time failure there is BLOCKED, never a FAIL.
const angle = {{ win32: "d3d11", darwin: "metal", linux: "vulkan" }}[process.platform as string] ?? "default";
const gl = ["--enable-gpu", "--ignore-gpu-blocklist", `--use-angle=${{angle}}`, "--enable-unsafe-swiftshader"];
// The Factory's refusing proxy, handed to the browser itself: Chromium ignores the proxy
// environment variables everywhere but Linux (wgflib.netguard).
const server = process.env["{proxy_var}"];
const proxy = server ? {{ proxy: {{ server, bypass: "{bypass}" }} }} : {{}};

export default defineConfig({{
  testDir: ".",
  testMatch: "browser_qa.spec.ts",
  outputDir: "test-results",
  workers: 1,
  fullyParallel: false,
  // A timing recording made on a degraded host is made again (browser-qa.yaml, timing checks).
  retries: {retries},
  timeout: {test_timeout_ms},
  reporter: [["line"]],
  use: {{ baseURL: "http://localhost:{port}", launchOptions: {{ args: gl }}, ...proxy }},
  projects: {projects},
  webServer: {{
    command: "pnpm preview --port {port} --strictPort",
    cwd: "{root}",
    port: {port},
    reuseExistingServer: false,
    timeout: 120_000,
  }},
}});
"""


# -- the contract -------------------------------------------------------------------------

CONTRACT_REF = "core/reference/browser-qa.yaml"
REFERENCED = ("environment", "muted_level")


def pinned_reader(context):
    """read(relpath) -> parsed YAML as the run pinned it (new-game `pinned_references`),
    the live file for a run that pinned none. Raises references.PinError when the run's copy
    is gone or was edited after the start."""
    environment = getattr(context, "environment", None) if context is not None else None
    run_dir = getattr(context, "run_dir", None) if context is not None else None

    def read(relpath):
        text, _digest, _pinned = pinned_references.read(relpath, environment, run_dir)
        return load_yaml(text)
    return read


def load_contract(path=None, reader=None):
    """The browser-QA contract. With `reader` (pinned_reader), the run's pinned copy, and
    the values it reads from other reference files resolved through the same reader."""
    contract = reader(CONTRACT_REF) if reader is not None else load_file(path or CONTRACT_PATH)
    if not isinstance(contract, dict) or not contract.get("checks"):
        raise ValueError(f"{paths.display(path or CONTRACT_PATH)} has no checks")
    if reader is not None:
        contract = dict(contract)
        contract["_resolved"] = {key: _referenced(contract, key, reader) for key in REFERENCED
                                 if contract.get(key)}
    return contract


def _referenced(contract, key, reader=None):
    """A value the contract reads from another reference file ({file, path})."""
    resolved = contract.get("_resolved") or {}
    if key in resolved:
        return resolved[key]
    ref = contract.get(key) or {}
    data = (reader("core/reference/" + ref["file"]) if reader is not None
            else load_file(os.path.join(paths.REFERENCE, ref["file"])))
    for part in ref.get("path") or ():
        data = (data or {}).get(part)
    return data


def environment_bars(contract):
    return _referenced(contract, "environment") or {}


def muted_level(contract):
    value = _referenced(contract, "muted_level")
    return float(value) if isinstance(value, (int, float)) else 0.001


def tier_class(context, config=None):
    """The run's quality-tier class (quality-policy.yaml tier.classes): the run's snapshot,
    else the installation's configured tier, else the policy's default."""
    policy = load_file(QUALITY_POLICY) or {}
    tiers = policy.get("tier") or {}
    tier = run_tier(getattr(context, "environment", None) if context is not None else None)
    if tier is None:
        strategy = ((config or {}).get("strategy") or {}) if isinstance(config, dict) else {}
        tier = strategy.get("quality_tier") or tiers.get("default")
    return tier, (tiers.get("classes") or {}).get(tier)


def required_for(definition, klass, contract, hard_profiles=()):
    """Whether a check of this definition is required for a run of tier class `klass`."""
    tier = definition.get("tier")
    flag = definition.get("hard_when_profile")
    if flag and flag in hard_profiles:
        tier = "hard"
    if tier == "hard":
        return True
    if tier == "quality":
        return klass in (contract.get("quality_required_at") or ())
    return False


# -- running the spec ---------------------------------------------------------------------

def _free_port():
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]


def settings(contract, design=None):
    """What the spec reads (WGF_BQA_CONFIG): the viewports, where the once-per-build
    measurements are made, the windows, and the declared actions with a sound."""
    bars = contract.get("bars") or {}
    outcomes = contract.get("outcomes") or {}
    experience = (((design or {}).get("build_spec") or {}).get("experience") or {})
    env = environment_bars(contract)
    return {
        "viewports": [dict(v) for v in contract.get("viewports") or []],
        "audio_viewport": contract.get("audio_viewport"),
        "perf_viewport": contract.get("perf_viewport"),
        "outcome_viewports": list(outcomes.get("viewports") or []),
        "start_timeout_ms": int((outcomes.get("start_timeout_s") or 30) * 1000),
        "ready_max_ms": int(((bars.get("load") or {}).get("ready_max_s") or 30) * 1000),
        "win_ms": int((outcomes.get("win_s") or 90) * 1000),
        "lose_ms": int((outcomes.get("lose_s") or 60) * 1000),
        "restart_ms": int((outcomes.get("restart_s") or 10) * 1000),
        # No design in the run: try for a win anyway; a game with none simply never reaches it.
        "has_win": bool(experience.get("win")) if experience else True,
        "action_audio": sorted({a.get("action") for a in experience.get("actions") or []
                                if isinstance(a, dict) and a.get("audio")} - {None}),
        "frames": {"sample_ms": int(((bars.get("frames") or {}).get("sample_s") or 8) * 1000),
                   "long_frame_ms": (bars.get("frames") or {}).get("long_frame_ms") or 100},
        "memory": {"session_ms": int(((bars.get("memory") or {}).get("session_s") or 45) * 1000)},
        "layout": {k: (bars.get("layout") or {}).get(k) for k in
                   ("critical_roles", "cover_samples", "cover_interval_ms")},
        "states": {"properties": list((bars.get("states") or {}).get("properties") or [])},
        "environment": {k: env.get(k) for k in ("tick_ms", "stall_ms", "max_stall_ms",
                                                "max_stalled_share", "max_server_wait_ms",
                                                "max_attempts")} if env else None,
        "retry_records": ["viewport", "perf"],
    }


def timeout_s(cfg):
    """The most the spec may take: every viewport's tests, every attempt, and start-up."""
    attempts = int((cfg.get("environment") or {}).get("max_attempts") or 1)
    start = cfg["start_timeout_ms"] / 1000.0
    per_viewport = 2 * start + 60
    outcome = (cfg["win_ms"] + cfg["lose_ms"] + cfg["restart_ms"]) / 1000.0 + 3 * start + 30
    perf = (cfg["frames"]["sample_ms"] + cfg["memory"]["session_ms"]) / 1000.0 + start + 60
    total = (attempts * len(cfg["viewports"]) * per_viewport + len(cfg["outcome_viewports"]) * outcome
             + attempts * perf + 60 + 180)
    return int(total)


def _test_timeout_ms(cfg):
    start = cfg["start_timeout_ms"]
    outcome = cfg["win_ms"] + cfg["lose_ms"] + cfg["restart_ms"] + 3 * start + 60000
    perf = cfg["frames"]["sample_ms"] + cfg["memory"]["session_ms"] + start + 90000
    return int(max(outcome, perf, 2 * start + 120000))


def write_runner(root, cfg, port=None):
    """(work dir, config path, out dir): the spec, its Playwright config and its settings,
    written under the checkout's build/; the records directory emptied first."""
    work = os.path.join(root, *WORK_DIR.split("/"))
    out = os.path.join(work, "out")
    shutil.rmtree(work, ignore_errors=True)
    os.makedirs(out)
    shutil.copy(SPEC, os.path.join(work, "browser_qa.spec.ts"))
    projects = []
    for v in cfg["viewports"]:
        use = {"viewport": {"width": v["width"], "height": v["height"]},
               "browserName": "chromium"}
        if v.get("touch"):
            use.update(isMobile=True, hasTouch=True, deviceScaleFactor=2)
        projects.append({"name": v["id"], "use": use})
    port = port or _free_port()
    attempts = int((cfg.get("environment") or {}).get("max_attempts") or 1)
    text = CONFIG.format(proxy_var=BROWSER_PROXY_VAR, bypass=BROWSER_BYPASS,
                         retries=max(0, attempts - 1), test_timeout_ms=_test_timeout_ms(cfg),
                         projects=json.dumps(projects), port=port,
                         root=root.replace("\\", "/"))
    # Not the game's config name: this one is the Factory's, beside its own spec.
    config_path = os.path.join(work, "browser-qa.config.ts")
    with open(config_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    with open(os.path.join(work, "settings.json"), "w", encoding="utf-8", newline="\n") as handle:
        json.dump(cfg, handle, indent=1)
    return work, config_path, out


def read_records(out, viewports):
    """{viewport id: {record name: record}} of what the spec wrote."""
    records = {}
    for v in viewports:
        vid = v["id"] if isinstance(v, dict) else v
        directory = os.path.join(out, vid)
        found = {}
        for name in ("viewport", "outcomes", "perf", "clips"):
            path = os.path.join(directory, f"{name}.json")
            if os.path.isfile(path):
                try:
                    with open(path, encoding="utf-8") as handle:
                        found[name] = json.load(handle)
                except ValueError:
                    found[name] = {"error": f"{name}.json is not JSON"}
        if found:
            records[vid] = found
    return records


def _hard_profiles(session):
    """The `hard_when_profile` flags a targeted platform's profile sets
    (`requirements.<flag>: true`)."""
    flags = set()
    for platform in session.platforms:
        profile, _source = session.profile(platform["id"])
        for key, value in ((profile or {}).get("requirements") or {}).items():
            if value is True:
                flags.add(key)
    return flags


def check_browser(session):
    """The verify step's browser-QA group: run the spec, then judge its records."""
    try:
        contract = load_contract(reader=pinned_reader(session.context))
    except (OSError, ValueError, pinned_references.PinError) as exc:
        return [session.record(Check(RUN_CHECK, "gameplay", "Browser QA ran", BLOCKED,
                                     message=f"the browser-QA contract cannot be read: {exc}",
                                     evidence=[Evidence("file", str(exc),
                                                        path=paths.display(CONTRACT_PATH))]))]
    mode = str(session.params.get("browser_qa") or "auto")
    tier, klass = tier_class(session.context, session.config)
    hard = _hard_profiles(session)
    if mode == "off":
        # Never a silent pass: switching browser QA off leaves every check it owns unmeasured.
        check = Check(RUN_CHECK, "gameplay", "Browser QA ran", BLOCKED if klass in (
            contract.get("quality_required_at") or ()) else WARNING,
            required=klass in (contract.get("quality_required_at") or ()),
            message="browser QA was switched off (with: browser_qa: off): its checks are not "
                    "measured, which a release-tier run does not pass",
            evidence=[Evidence("reference", "with: browser_qa: off")])
        return [session.record(check)]
    if not session.passed("build.build"):
        return [session.record(session.blocked_by("build.build", id=RUN_CHECK,
                                                  category="gameplay", title="Browser QA ran"))]
    cfg = settings(contract, session.inputs.get("game-design"))
    work, config_path, out = write_runner(session.root, cfg)
    session.timeouts.setdefault("browser_qa", timeout_s(cfg))
    command = session.exec_command("playwright", "test", "-c",
                                   os.path.relpath(config_path, session.root).replace(os.sep, "/"))
    result = session.run(command, "browser_qa",
                         env={"WGF_BQA_OUT": out, "WGF_BQA_CONFIG": os.path.join(work, "settings.json")})
    records = read_records(out, cfg["viewports"])
    output = "\n".join(p for p in (result.stdout, result.stderr) if p)
    run_evidence = [Evidence.of_command(result,
                                        summary=f"browser QA spec: {result.describe()}"),
                    Evidence("file", f"records for {len(records)} of {len(cfg['viewports'])} "
                                     "viewport(s)", path=f"{WORK_DIR}/out")]
    if not records:
        why = ("no browser to run it in (playwright install chromium)"
               if any(m in output for m in _NO_BROWSER) else
               result.describe() if result.unavailable else
               "the spec wrote no records")
        return [session.record(Check(RUN_CHECK, "gameplay", "Browser QA ran", BLOCKED,
                                     message=why, evidence=run_evidence))]
    run = session.record(Check(RUN_CHECK, "gameplay", "Browser QA ran", PASS,
                               message=f"recorded {len(records)} viewport(s): "
                                       + ", ".join(sorted(records)),
                               evidence=run_evidence))
    bundle = scan_bundle(session.path(session.output_dir))
    checks = judge(records, contract, klass=klass, hard_profiles=hard, bundle=bundle,
                   records_path=f"{WORK_DIR}/out", tier=tier)
    session.browser_qa = {"records": records, "checks": checks, "bundle": bundle}
    return [run] + [session.record(c) for c in checks]


# -- the bundle, offline ------------------------------------------------------------------

def scan_bundle(directory):
    """Every image and audio file under the built bundle: its size, and an image's pixel
    dimensions (wgf_assets.formats.sniff) or an audio file's duration (wgf_assets.audiofile)."""
    from wgf_assets import audiofile, formats
    out = {"images": [], "audio": [], "root": directory}
    if not os.path.isdir(directory):
        return out
    for base, dirs, files in os.walk(directory):
        dirs[:] = sorted(dirs)
        for name in sorted(files):
            path = os.path.join(base, name)
            rel = os.path.relpath(path, directory).replace(os.sep, "/")
            lower = name.lower()
            if lower.endswith(IMAGE_EXT):
                with open(path, "rb") as handle:
                    data = handle.read()
                found = formats.sniff(data)
                out["images"].append({"path": rel, "bytes": len(data),
                                      "width": getattr(found, "width", None),
                                      "height": getattr(found, "height", None)})
            elif lower.endswith(AUDIO_EXT):
                with open(path, "rb") as handle:
                    data = handle.read()
                try:
                    duration = audiofile.read(data).duration_s
                except (audiofile.AudioError, ValueError, struct.error):
                    duration = None
                out["audio"].append({"path": rel, "bytes": len(data), "duration_s": duration})
    return out


# -- judging ------------------------------------------------------------------------------

class _Judge:
    def __init__(self, contract, klass, hard_profiles, bundle, records_path, skip=None):
        self.contract = contract
        self.klass = klass
        self.skip = skip if skip is not None else omission_policy(None, klass)
        self.hard = set(hard_profiles or ())
        self.bars = contract.get("bars") or {}
        self.defs = {c["id"]: c for c in contract.get("checks") or []}
        self.env = environment_bars(contract)
        self.muted = muted_level(contract)
        self.bundle = bundle or {}
        self.path = records_path
        self.out = []

    # One check, from a verdict: pass | fail | unmeasured (a WARNING: nothing of that kind to
    # measure) | blocked (could not be measured: BLOCKED where required).
    def emit(self, cid, viewport, verdict, message, data=None):
        definition = self.defs[cid]
        required = required_for(definition, self.klass, self.contract, self.hard)
        tier = "hard" if (definition.get("hard_when_profile") in self.hard) else definition["tier"]
        if verdict == "pass":
            status = PASS
        elif verdict == "fail":
            status = FAIL if required else WARNING
        elif verdict == "blocked":
            status = BLOCKED if required else WARNING
        elif verdict == "omitted":
            # The build omits what the check reads: held like a skipped check at this tier.
            required = definition.get("tier") != "advisory" and self.skip.required(
                f"browser.{cid}", steps=("verify",))
            status = BLOCKED if required else WARNING
            if required:
                message = f"{message} - {self.skip.describe()}"
        else:
            status, required = WARNING, False
        check_id = f"browser.{cid}" + (f":{viewport}" if viewport else "")
        where = f"{self.path}/{viewport}" if viewport else self.path
        evidence = [Evidence("observation", f"{tier} tier: {message}"[:500], path=where,
                             data={"tier": tier, "verdict": verdict, **(data or {})})]
        self.out.append(Check(check_id, definition.get("category", "gameplay"),
                              definition.get("what", cid)[:160], status, required=required,
                              message=f"[{tier}] {message}", evidence=evidence))

    # -- per viewport -----------------------------------------------------------------------

    def viewport(self, vid, recs, size):
        vp = recs.get("viewport")
        if not isinstance(vp, dict):
            for cid in ("loads", "canvas", "ready", "menus", "load-time", "first-interaction",
                        "page-errors", "console-errors", "webgl-context", "context-menu",
                        "pause-resume", "hidden-pause", "overflow", "clipping", "ui-overlap",
                        "ui-covers-play", "safe-margins", "button-states"):
                self.emit(cid, vid, "blocked", "the spec recorded nothing on this viewport")
            return
        started = vp.get("started") or {}
        watch = vp.get("watch") or {}
        origin = _origin(watch)
        layouts = [l for l in vp.get("layouts") or [] if isinstance(l, dict) and "viewport" in l]
        layouts += [l for l in (recs.get("outcomes") or {}).get("layouts") or []
                    if isinstance(l, dict) and "viewport" in l]

        # loads
        if started.get("error"):
            self.emit("loads", vid, "fail", f"the page did not load: {started['error']}")
        else:
            failed = [f for f in watch.get("failed_requests") or []
                      if _same_origin(f.get("url"), origin) and not _favicon(f.get("url"))]
            if failed:
                self.emit("loads", vid, "fail", f"{len(failed)} request(s) of the game's own origin "
                          "failed: " + "; ".join(f"{_path(f['url'])} "
                                                 f"({f.get('status') or f.get('error')})"
                                                 for f in failed[:5]), {"failed": failed[:20]})
            else:
                self.emit("loads", vid, "pass", "the document and everything the game fetched "
                          "from its origin answered")

        # canvas
        shares = [c.get("share") or 0 for l in layouts for c in l.get("canvases") or []]
        floor = (self.bars.get("load") or {}).get("min_canvas_share", 0.25)
        if not layouts:
            self.emit("canvas", vid, "blocked", "no screen was measured")
        elif shares and max(shares) >= floor:
            self.emit("canvas", vid, "pass", f"a canvas covers {max(shares):.0%} of the viewport")
        else:
            self.emit("canvas", vid, "fail", f"no canvas covers {floor:.0%} of the viewport "
                      f"(largest {max(shares) if shares else 0:.0%})")

        # ready, menus
        ready_max = (self.bars.get("load") or {}).get("ready_max_s", 30)
        ready_ms = started.get("ready_ms")
        if ready_ms is None and isinstance(started.get("tti_ms"), (int, float)):
            ready_ms = started["tti_ms"]
        if ready_ms is not None and ready_ms <= ready_max * 1000:
            self.emit("ready", vid, "pass", f"loading completed at {ready_ms / 1000:.2f} s")
        else:
            self.emit("ready", vid, "fail",
                      "loading did not complete" + ("" if started.get("probe") else
                                                    " (the play probe never answered)")
                      + f" within {ready_max} s; states seen: {started.get('states')}")
        if started.get("playing_ms") is not None:
            self.emit("menus", vid, "pass", f"into play through {started.get('states')} by "
                      f"{', '.join(started.get('began') or []) or 'no input'}")
        else:
            self.emit("menus", vid, "fail", "play never started: states seen "
                      f"{started.get('states')}, inputs pressed {started.get('began')}")

        # timing
        health = self.health(vp)
        load_bar = (self.bars.get("load") or {}).get("max_load_s", 6)
        self.timed("load-time", vid, ready_ms, load_bar, "loading completed", health)
        first_bar = (self.bars.get("load") or {}).get("max_first_interaction_s", 8)
        self.timed("first-interaction", vid, started.get("interactive_ms"), first_bar,
                   "the first input was offered", health)

        # runtime health
        errors = []
        for name in ("viewport", "outcomes", "perf"):
            ow = (recs.get(name) or {}).get("watch") or {}
            errors += list(ow.get("page_errors") or []) + _in_page(ow, "rejections")
        if errors:
            self.emit("page-errors", vid, "fail", f"{len(errors)} uncaught: "
                      + " | ".join(sorted(set(errors))[:3]), {"errors": sorted(set(errors))[:20]})
        else:
            self.emit("page-errors", vid, "pass", "no uncaught exception or rejection")
        own, ignored = self.console(recs)
        limit = (self.contract.get("console") or {}).get("max_errors", 0)
        if len(own) > limit:
            self.emit("console-errors", vid, "fail", f"{len(own)} console error(s) from the "
                      "game: " + " | ".join(e["text"] for e in own[:3]),
                      {"errors": own[:20], "ignored": len(ignored)})
        else:
            self.emit("console-errors", vid, "pass", "no console error from the game's origin"
                      + (f" ({len(ignored)} about refused or foreign requests, not the game's)"
                         if ignored else ""), {"ignored": ignored[:10]})
        lost = []
        for name in ("viewport", "outcomes", "perf"):
            lost += _in_page((recs.get(name) or {}).get("watch"), "context_lost")
        if lost:
            self.emit("webgl-context", vid, "fail", f"the WebGL context was lost {len(lost)} time(s)")
        else:
            self.emit("webgl-context", vid, "pass", "no WebGL context was lost")
        self.context_menu(vid, vp)
        self.pause(vid, vp)
        self.hidden_pause(vid, vp)
        self.layout(vid, layouts, size)
        self.cover(vid, vp)
        self.states(vid, vp)

    def health(self, record):
        """(degraded on the last attempt, reasons, attempts) of a timing record."""
        from wgf_playability.analysis import environment_health
        attempts = []
        for entry in record.get("attempts") or []:
            if isinstance(entry, dict):
                degraded, reasons = environment_health(entry.get("health"), self.env)
                attempts.append({"attempt": entry.get("attempt"), "degraded": bool(degraded),
                                 "reasons": reasons})
        if not attempts and isinstance(record.get("health"), dict):
            degraded, reasons = environment_health(record["health"], self.env)
            attempts.append({"attempt": 1, "degraded": bool(degraded), "reasons": reasons})
        last = attempts[-1] if attempts else {"degraded": False, "reasons": []}
        return {"degraded": last["degraded"], "reasons": last["reasons"], "attempts": attempts}

    def timed(self, cid, vid, value_ms, bar_s, what, health):
        data = {"measured_ms": value_ms, "bar_s": bar_s, "environment": health["attempts"]}
        if health["degraded"]:
            self.emit(cid, vid, "blocked",
                      f"not judged: the host was degraded on every attempt "
                      f"({'; '.join(health['reasons'][:3])}); {what} at "
                      f"{_secs(value_ms)} - re-measure on a quiet host: a degraded host never "
                      "passes or fails a timing check", data)
        elif value_ms is None:
            self.emit(cid, vid, "fail", f"{what}: never", data)
        elif value_ms <= bar_s * 1000:
            self.emit(cid, vid, "pass", f"{what} at {_secs(value_ms)} (bar {bar_s} s)", data)
        else:
            self.emit(cid, vid, "fail", f"{what} at {_secs(value_ms)}, over the {bar_s} s bar", data)

    def console(self, recs):
        patterns = [re.compile(re.escape(p), re.I)
                    for p in (self.contract.get("console") or {}).get("ignore_patterns") or ()]
        own, ignored = [], []
        for name in ("viewport", "outcomes", "perf"):
            watch = (recs.get(name) or {}).get("watch") or {}
            origin = _origin(watch)
            for entry in watch.get("console") or []:
                if entry.get("type") != "error":
                    continue
                url = entry.get("url") or ""
                if any(p.search(entry.get("text") or "") for p in patterns) or (
                        url and origin and not _same_origin(url, origin)):
                    ignored.append(entry)
                else:
                    own.append(entry)
        return own, ignored

    def context_menu(self, vid, vp):
        probe = vp.get("context_menu")
        if not isinstance(probe, dict) or not probe.get("probed"):
            reason = (probe or {}).get("reason") if isinstance(probe, dict) else None
            self.emit("context-menu", vid, "blocked" if vp.get("started", {}).get("playing_ms")
                      is not None else "unmeasured",
                      f"not probed: {reason or 'play never started'}")
            return
        events = probe.get("events") or []
        how = probe.get("how")
        if not events:
            # A long press that raised no contextmenu event opened nothing either.
            verdict = "pass" if how == "long-press" else "blocked"
            self.emit("context-menu", vid, verdict,
                      f"the {how} raised no contextmenu event" + (
                          ": nothing opens" if verdict == "pass" else
                          ": the probe could not establish whether a menu opens"), probe)
            return
        open_ = [e for e in events if not e.get("prevented")]
        if open_:
            self.emit("context-menu", vid, "fail",
                      f"a {how} on the game opens the browser's context menu: the game does not "
                      f"prevent contextmenu (target {open_[0].get('target')})", probe)
        else:
            self.emit("context-menu", vid, "pass", f"a {how} on the game is prevented", probe)

    def pause(self, vid, vp):
        pause = vp.get("pause")
        if not isinstance(pause, dict) or not pause.get("tried"):
            self.emit("pause-resume", vid, "unmeasured",
                      f"not tried: {(pause or {}).get('reason') or 'play never started'}")
            return
        if not pause.get("paused"):
            if pause.get("declared") or pause.get("how") == "button":
                self.emit("pause-resume", vid, "fail",
                          f"the game's pause control ({pause.get('how')}) did not pause play", pause)
            else:
                self.emit("pause-resume", vid, "unmeasured",
                          "no pause control (probe input or button), and Escape does not pause", pause)
            return
        if pause.get("resumed"):
            self.emit("pause-resume", vid, "pass", f"paused and resumed by {pause.get('how')}",
                      {"how": pause.get("how")})
        else:
            self.emit("pause-resume", vid, "fail", f"paused by {pause.get('how')} but did not "
                      "resume to play", {"how": pause.get("how")})

    def hidden_pause(self, vid, vp):
        hidden = vp.get("hidden")
        if not isinstance(hidden, dict) or not hidden.get("tried"):
            self.emit("hidden-pause", vid, "blocked" if (vp.get("started") or {}).get("playing_ms")
                      is not None else "unmeasured",
                      f"not tried: {(hidden or {}).get('reason') or 'play never started'}")
            return
        states = hidden.get("state_hidden") or []
        held = hidden.get("still") or any(s == "paused" for s in states)
        if not held:
            self.emit("hidden-pause", vid, "fail", "with the page hidden play went on: the game "
                      f"kept moving (states {states})", hidden)
        elif not hidden.get("resumed_by"):
            self.emit("hidden-pause", vid, "fail", "play held while hidden but could not be "
                      f"resumed when shown again (state {hidden.get('state_after')})", hidden)
        else:
            self.emit("hidden-pause", vid, "pass", f"held while hidden ({states}); resumed by "
                      f"{hidden.get('resumed_by')}", hidden)

    def layout(self, vid, layouts, size):
        bars = self.bars.get("layout") or {}
        if not layouts:
            for cid in ("overflow", "clipping", "ui-overlap", "safe-margins"):
                self.emit(cid, vid, "blocked", "no screen was measured")
            return
        over, clips, overlaps, margins = [], [], [], []
        for layout in layouts:
            state = layout.get("state")
            vw, vh = layout.get("viewport") or size
            sw, sh = layout.get("scroll") or (vw, vh)
            extra = max(sw - vw, sh - vh)
            if extra > bars.get("max_overflow_px", 2):
                over.append(f"{state}: the page scrolls {sw}x{sh} in {vw}x{vh}")
            items = ([("control", c) for c in layout.get("controls") or []]
                     + [("text", t) for t in layout.get("texts") or []])
            for kind, item in items:
                x, y, w, h = item.get("box") or (0, 0, 0, 0)
                cut = max(-x, -y, x + w - vw, y + h - vh)
                if cut > bars.get("max_clip_px", 2):
                    clips.append(f"{state}: {kind} '{item.get('text')}' cut by {round(cut)} px")
            controls = [c for c in layout.get("controls") or [] if c.get("box")]
            for i, a in enumerate(controls):
                for b in controls[i + 1:]:
                    area = _overlap(a["box"], b["box"])
                    if area > bars.get("max_overlap_px2", 16):
                        overlaps.append(f"{state}: '{a.get('text')}' and '{b.get('text')}' "
                                        f"overlap {round(area)} px2")
                for t in layout.get("texts") or []:
                    area = _overlap(a["box"], t.get("box") or (0, 0, 0, 0))
                    if area > bars.get("max_overlap_px2", 16):
                        overlaps.append(f"{state}: control '{a.get('text')}' covers text "
                                        f"'{t.get('text')}' ({round(area)} px2)")
                x, y, w, h = a["box"]
                gap = min(x, y, vw - (x + w), vh - (y + h))
                if gap < bars.get("safe_margin_px", 4):
                    margins.append(f"{state}: '{a.get('text')}' is {round(gap)} px from the edge")
        states = sorted({l.get("state") for l in layouts})
        self.emit("overflow", vid, "fail" if over else "pass",
                  "; ".join(over[:4]) if over else f"no scrolling on {states}", {"found": over[:20]})
        self.emit("clipping", vid, "fail" if clips else "pass",
                  "; ".join(clips[:4]) if clips else f"nothing cut on {states}", {"found": clips[:20]})
        self.emit("ui-overlap", vid, "fail" if overlaps else "pass",
                  "; ".join(overlaps[:4]) if overlaps else f"no overlap on {states}",
                  {"found": overlaps[:20]})
        self.emit("safe-margins", vid, "fail" if margins else "pass",
                  "; ".join(margins[:4]) if margins else f"every control keeps "
                  f"{bars.get('safe_margin_px', 4)} px on {states}", {"found": margins[:20]})

    def cover(self, vid, vp):
        bar = (self.bars.get("layout") or {}).get("max_entity_cover_share", 0.25)
        samples = vp.get("cover")
        if not isinstance(samples, list) or not samples:
            self.emit("ui-covers-play", vid, "blocked" if (vp.get("started") or {}).get("playing_ms")
                      is not None else "unmeasured", "no entity was sampled during play")
            return
        seen = [e for sample in samples for e in sample or []]
        if not seen:
            self.emit("ui-covers-play", vid, "omitted", "the probe reported no visible "
                      "gameplay-critical entity during play")
            return
        persist = max(1, int((self.bars.get("layout") or {}).get("min_cover_samples", 1)))
        worst, streak, persisted = {}, {}, {}
        for sample in samples:
            now = {}
            for e in sample or []:
                key = (e.get("role"), e.get("kind") or e.get("id"))
                if e.get("share", 0) > worst.get(key, {}).get("share", -1):
                    worst[key] = e
                if e.get("share", 0) > bar and e["share"] > now.get(key, {}).get("share", -1):
                    now[key] = e
            for key in streak:
                if key not in now:
                    streak[key] = 0
            for key, e in now.items():
                streak[key] = streak.get(key, 0) + 1
                if streak[key] >= persist and e["share"] > persisted.get(key, {}).get("share", -1):
                    persisted[key] = e
        bad = sorted(persisted.values(),
                     key=lambda e: -e["share"])
        if bad:
            self.emit("ui-covers-play", vid, "fail", "; ".join(
                f"{e['role']} {e.get('kind') or e.get('id')} {e['share']:.0%} covered by {e.get('by')}"
                for e in bad[:4]), {"covered": bad[:20]})
        else:
            top = max(worst.values(), key=lambda e: e.get("share", 0))
            self.emit("ui-covers-play", vid, "pass", f"{len(worst)} entity kind(s) sampled; at "
                      f"most {top.get('share', 0):.0%} covered", {"worst": top})

    def states(self, vid, vp):
        measured = vp.get("control_states") or {}
        controls = measured.get("controls") or []
        if not measured.get("measured") or not controls:
            self.emit("button-states", vid, "unmeasured", "no control on the title screen to "
                      "measure" if measured.get("measured") else
                      f"not measured: {measured.get('error') or 'the page did not settle'}")
            return
        flat, notes = [], []
        enabled = [c for c in controls if not c.get("disabled")]
        for c in enabled:
            for state in ("hover", "pressed"):
                if c.get(state) is not None and c[state] == c.get("rest"):
                    flat.append(f"'{c.get('text')}' {state} looks like rest")
        for c in controls:
            if c.get("disabled") and enabled and all(c.get("rest") == e.get("rest") for e in enabled):
                flat.append(f"disabled '{c.get('text')}' looks enabled")
        if not any(c.get("hover") is not None for c in enabled):
            notes.append("touch viewport: hover and pressed not probed")
        self.emit("button-states", vid, "fail" if flat else "pass",
                  "; ".join(flat[:4]) if flat else f"{len(controls)} control(s) show their states"
                  + (f" ({notes[0]})" if notes else ""), {"flat": flat[:20]})

    # -- end states -------------------------------------------------------------------------

    def outcomes(self, vid, recs):
        oc = recs.get("outcomes")
        if not isinstance(oc, dict):
            for cid in ("win", "lose", "restart"):
                self.emit(cid, vid, "blocked", "the spec recorded no end states on this viewport")
            return
        if oc.get("error"):
            note = f" (the run stopped: {oc['error'][:120]})"
        else:
            note = ""
        win = oc.get("win")
        if "win_started" not in oc:
            self.emit("win", vid, "unmeasured", "the design states no win")
        elif not isinstance(win, dict):
            self.emit("win", vid, "blocked", "play never started for the win run" + note)
        elif win.get("reached") == "won":
            self.emit("win", vid, "pass", "the oracle reached won")
        elif win.get("reached") == "lost":
            self.emit("win", vid, "fail", "the oracle, playing well, lost on this viewport")
        else:
            self.emit("win", vid, "unmeasured", f"won not reached within {win.get('window_ms', 0) / 1000:.0f} s "
                      "(the playability step judges win.reachable over its own window)" + note)
        lose = oc.get("lose")
        if not isinstance(lose, dict):
            self.emit("lose", vid, "blocked", "play never started for the lose run" + note)
            self.emit("restart", vid, "blocked", "no lost state to restart from" + note)
            return
        if lose.get("reached") == "lost":
            self.emit("lose", vid, "pass", "bad play reached lost")
        else:
            self.emit("lose", vid, "unmeasured", f"lost not reached within "
                      f"{lose.get('window_ms', 0) / 1000:.0f} s of bad play" + note)
            self.emit("restart", vid, "unmeasured", "no lost state to restart from")
            return
        restart = oc.get("restart") or {}
        if restart.get("reached") == "playing":
            self.emit("restart", vid, "pass", f"back in play {restart.get('took_ms')} ms after "
                      f"{restart.get('how')}")
        elif not restart.get("how"):
            self.emit("restart", vid, "fail", "the lost screen offers no retry (probe input or button)")
        else:
            self.emit("restart", vid, "fail", f"{restart.get('how')} did not return to play within "
                      f"{restart.get('window_ms', 0) / 1000:.0f} s")

    # -- audio ------------------------------------------------------------------------------

    def audio(self, vid, recs, clips_record, action_audio):
        bars = self.bars.get("audio") or {}
        vp = recs.get("viewport") if isinstance(recs, dict) else None
        oc = recs.get("outcomes") if isinstance(recs, dict) else None
        clips = (clips_record or {}).get("clips") or {}
        clip_list = clips.get("clips") if isinstance(clips, dict) else None
        by_url = {}
        for c in clip_list or []:
            by_url[_asset_key(c.get("url"))] = c

        # audio-events
        runs = []
        if isinstance(vp, dict):
            runs.append((((vp.get("watch") or {}).get("runs") or {}).get("main") or {},
                         [vp.get("played") or {}]))
        if isinstance(oc, dict):
            played = oc.get("played") or {}
            for name in ("win", "lose"):
                runs.append((((oc.get("watch") or {}).get("runs") or {}).get(name) or {},
                             [played.get(name) or {}]))
        runs = [r for r in runs if r]
        degraded = [self.health(r)["reasons"] for r in (vp, oc)
                    if isinstance(r, dict) and self.health(r)["degraded"]]
        if not runs:
            self.emit("audio-events", None, "blocked", f"nothing recorded on {vid}")
        else:
            self.audio_events(runs, action_audio, bars, degraded)

        # audio-loops: every sound any record on any viewport started.
        all_sounds = []
        for record in (vp, oc, recs.get("perf") if isinstance(recs, dict) else None):
            if isinstance(record, dict):
                all_sounds += _in_page(record.get("watch"), "sounds")
        loops = self.loops(all_sounds, by_url, bars)
        if not all_sounds:
            self.emit("audio-loops", None, "unmeasured", "the page started no sound")
        elif loops["bad"]:
            self.emit("audio-loops", None, "fail", "one-shot clip(s) started looping: "
                      + ", ".join(loops["bad"][:5]), loops)
        else:
            self.emit("audio-loops", None, "pass", f"{len(all_sounds)} sound start(s); every "
                      f"looping one is a looping clip ({', '.join(loops['looped'][:4]) or 'none looped'})"
                      + (f"; unidentified short loops: {', '.join(loops['unknown'][:3])}"
                         if loops["unknown"] else ""), loops)

        # audio-mute
        mute = (vp or {}).get("mute") if isinstance(vp, dict) else None
        if not isinstance(mute, dict):
            self.emit("audio-mute", None, "blocked", f"the mute control was not probed on {vid}")
        elif not mute.get("tried"):
            self.emit("audio-mute", None, "unmeasured", mute.get("reason") or "no mute control")
        else:
            before = _level(mute.get("before"))
            muted = _level(mute.get("muted"))
            unmuted = _level(mute.get("unmuted"))
            if before is None or before <= self.muted:
                self.emit("audio-mute", None, "unmeasured", f"nothing was audible before the mute "
                          f"control was pressed (level {before})", mute)
            elif muted is None or muted > self.muted:
                self.emit("audio-mute", None, "fail", f"{mute.get('how')} left the master level at "
                          f"{muted} (silent is at most {self.muted})", mute)
            elif unmuted is None or unmuted <= self.muted:
                self.emit("audio-mute", None, "fail", f"{mute.get('how')} silenced the game but "
                          f"pressing it again did not bring the sound back (level {unmuted})", mute)
            else:
                self.emit("audio-mute", None, "pass", f"{mute.get('how')} silences "
                          f"({before} -> {muted}) and restores ({unmuted})", mute)

        # audio-hidden
        hidden = (vp or {}).get("hidden") if isinstance(vp, dict) else None
        if not isinstance(hidden, dict) or not hidden.get("tried"):
            self.emit("audio-hidden", None, "blocked" if isinstance(vp, dict) and
                      (vp.get("started") or {}).get("playing_ms") is not None else "unmeasured",
                      f"the page was not hidden during play on {vid}: "
                      f"{(hidden or {}).get('reason') or 'not tried'}"
                      + (f" (back into play: {hidden.get('reentered')})"
                         if isinstance(hidden, dict) and hidden.get("reentered") else ""))
        elif hidden.get("audio_hidden") is None:
            self.emit("audio-hidden", None, "omitted", "the play probe reports no audio")
        else:
            before = _level(hidden.get("audio_before"))
            after = _level(hidden.get("audio_hidden"))
            if after is not None and after > self.muted:
                self.emit("audio-hidden", None, "fail", f"with the page hidden the master level "
                          f"is {after} (silent is at most {self.muted})", hidden)
            elif before is None or before <= self.muted:
                self.emit("audio-hidden", None, "unmeasured", "nothing was audible before the page "
                          f"was hidden (level {before}): silence while hidden proves nothing", hidden)
            else:
                self.emit("audio-hidden", None, "pass", f"hidden: {before} -> {after}", hidden)

    def audio_events(self, runs, action_audio, bars, degraded=()):
        window = bars.get("action_window_ms", 500)
        outcome_window = bars.get("outcome_window_ms", 2500)
        lead = bars.get("outcome_lead_ms", 0)
        per_action = {a: [0, 0] for a in action_audio}
        outcomes = {}
        for sounds_holder, logs in runs:
            sounds = sorted(s.get("t", 0) for s in sounds_holder.get("sounds") or [])
            for log in logs:
                for entry in log.get("inputs") or []:
                    action = entry.get("action")
                    if action in per_action:
                        per_action[action][1] += 1
                        if _sound_within(sounds, entry.get("t"), window):
                            per_action[action][0] += 1
                for move in log.get("transitions") or []:
                    if move.get("state") in ("won", "lost"):
                        hit = _sound_within(sounds, move.get("t"), outcome_window, lead)
                        got = outcomes.setdefault(move["state"], [0, 0])
                        got[1] += 1
                        got[0] += int(hit)
        silent = [f"{a} (0 of {n})" for a, (h, n) in per_action.items() if n and not h]
        silent += [f"{s} (0 of {n})" for s, (h, n) in outcomes.items() if n and not h]
        taken = {a: f"{h}/{n}" for a, (h, n) in per_action.items() if n}
        untaken = [a for a, (_h, n) in per_action.items() if not n]
        data = {"actions": taken, "outcomes": {s: f"{h}/{n}" for s, (h, n) in outcomes.items()},
                "not_taken": untaken}
        if silent and degraded:
            # A window missed on a stalled host says nothing: a sound that followed in it
            # stands, a silence is re-measured.
            self.emit("audio-events", None, "blocked", "no sound after: " + ", ".join(silent)
                      + " - on a degraded host (" + "; ".join(degraded[0][:2])
                      + "): re-measure on a quiet host", data)
        elif silent:
            self.emit("audio-events", None, "fail", "no sound after: " + ", ".join(silent), data)
        elif not taken and not outcomes:
            self.emit("audio-events", None, "unmeasured", "no declared action with a sound was "
                      "taken and no end state was reached", data)
        else:
            self.emit("audio-events", None, "pass", "a sound follows "
                      + ", ".join(f"{k} {v}" for k, v in {**taken, **data["outcomes"]}.items())
                      + (f"; not taken here: {', '.join(untaken)}" if untaken else ""), data)

    def loops(self, sounds, by_url, bars):
        bad, looped, unknown = [], [], []
        limit = bars.get("oneshot_max_s", 6)
        for s in sounds:
            if not (s.get("loop") or s.get("loop_now")):
                continue
            clip = by_url.get(_asset_key(s.get("url"))) if s.get("url") else None
            name = (clip or {}).get("id") or _path(s.get("url")) or f"{s.get('kind')} {s.get('duration')} s"
            if clip is not None:
                if clip.get("loop") is True or clip.get("type") == "music":
                    looped.append(name)
                else:
                    bad.append(name)
            elif s.get("url") and s.get("duration") is not None and s["duration"] <= limit:
                bad.append(name)
            elif s.get("duration") is not None and s["duration"] <= limit:
                unknown.append(name)
            else:
                looped.append(name)
        return {"bad": sorted(set(bad)), "looped": sorted(set(looped)),
                "unknown": sorted(set(unknown))}

    def clips(self, clips_record):
        bars = self.bars.get("audio") or {}
        if not isinstance(clips_record, dict):
            self.emit("audio-clips", None, "blocked", "the shipped clips were not measured")
            self.emit("audio-loudness", None, "blocked", "the shipped clips were not measured")
            return
        clips = clips_record.get("clips") or {}
        if clips_record.get("error") or not isinstance(clips, dict):
            self.emit("audio-clips", None, "blocked", f"not measured: {clips_record.get('error')}")
            self.emit("audio-loudness", None, "blocked", f"not measured: {clips_record.get('error')}")
            return
        if clips.get("manifest") != 200:
            self.emit("audio-clips", None, "omitted", f"no runtime manifest (assets.json: "
                      f"{clips.get('manifest')})")
            self.emit("audio-loudness", None, "omitted", "no runtime manifest")
            return
        listed = clips.get("clips") or []
        broken = [f"{c.get('id')} ({c.get('error') or c.get('status')})" for c in listed
                  if c.get("error") or c.get("status") != 200 or c.get("duration_s") is None]
        if not listed:
            self.emit("audio-clips", None, "unmeasured", "the runtime manifest lists no audio")
        elif broken:
            self.emit("audio-clips", None, "fail", "missing or undecodable: " + ", ".join(broken[:6]),
                      {"broken": broken})
        else:
            self.emit("audio-clips", None, "pass", f"{len(listed)} clip(s) fetched and decoded")
        gate = bars.get("gate_dbfs", -50)
        measured = []
        for c in listed:
            loud = gated_loudness(c.get("blocks_db") or [], gate)
            if loud is None:
                continue
            kind = "music" if c.get("type") == "music" else "sfx"
            measured.append({"id": c.get("id"), "kind": kind, "loudness_db": loud,
                             "peak_dbfs": c.get("peak_dbfs")})
        if len(measured) < 2:
            self.emit("audio-loudness", None, "unmeasured", "fewer than two clips with sound to "
                      "compare", {"clips": measured})
            return
        problems = []
        sfx = [m for m in measured if m["kind"] == "sfx"]
        music = [m for m in measured if m["kind"] == "music"]
        if len(sfx) >= 2:
            loud, quiet = max(sfx, key=lambda m: m["loudness_db"]), min(sfx, key=lambda m: m["loudness_db"])
            spread = loud["loudness_db"] - quiet["loudness_db"]
            if spread > bars.get("max_sfx_spread_db", 20):
                problems.append(f"effects spread {spread:.1f} dB ({loud['id']} "
                                f"{loud['loudness_db']:.1f} vs {quiet['id']} {quiet['loudness_db']:.1f})")
        if sfx and music:
            gap = (statistics.median(m["loudness_db"] for m in music)
                   - statistics.median(m["loudness_db"] for m in sfx))
            if gap > bars.get("max_music_over_sfx_db", 3):
                problems.append(f"music sits {gap:.1f} dB over the effects")
            elif -gap > bars.get("max_music_under_sfx_db", 24):
                problems.append(f"music sits {-gap:.1f} dB under the effects")
        clipped = [m["id"] for m in measured if isinstance(m.get("peak_dbfs"), (int, float))
                   and m["peak_dbfs"] >= bars.get("clip_peak_dbfs", -0.1)]
        if clipped:
            problems.append("clipping: " + ", ".join(clipped[:6]))
        data = {"clips": sorted(measured, key=lambda m: m["loudness_db"])}
        if problems:
            self.emit("audio-loudness", None, "fail", "; ".join(problems), data)
        else:
            self.emit("audio-loudness", None, "pass", f"{len(measured)} clip(s) balanced "
                      f"({min(m['loudness_db'] for m in measured):.1f} to "
                      f"{max(m['loudness_db'] for m in measured):.1f} dB)", data)

    # -- performance -------------------------------------------------------------------------

    def perf(self, vid, perf):
        bars = self.bars.get("frames") or {}
        if not isinstance(perf, dict):
            self.emit("frame-stability", None, "blocked", f"no performance run on {vid}")
            self.emit("memory-growth", None, "blocked", f"no performance run on {vid}")
            return
        health = self.health(perf)
        frames = perf.get("frames") or {}
        deltas = [d for d in frames.get("deltas") or [] if isinstance(d, (int, float))][10:]
        renderer = str(perf.get("renderer") or "")
        software = any(s.lower() in renderer.lower()
                       for s in self.contract.get("software_renderers") or ())
        data = {"renderer": renderer, "environment": health["attempts"]}
        if health["degraded"]:
            for cid in ("frame-stability", "memory-growth"):
                self.emit(cid, None, "blocked", "not judged: the host was degraded on every "
                          f"attempt ({'; '.join(health['reasons'][:3])}) - re-measure on a quiet "
                          "host", data)
            return
        if len(deltas) < 30:
            self.emit("frame-stability", None, "blocked", f"only {len(deltas)} frame(s) measured "
                      "during play" + (f" ({perf.get('error')})" if perf.get("error") else ""), data)
        else:
            p95 = _percentile(deltas, 95)
            long_ = sum(1 for d in deltas if d >= bars.get("long_frame_ms", 100)) / len(deltas)
            data.update(p95_ms=round(p95, 2), median_ms=round(statistics.median(deltas), 2),
                        long_share=round(long_, 4), frames=len(deltas))
            bad = []
            if p95 > bars.get("max_p95_ms", 33.4):
                bad.append(f"p95 frame time {p95:.1f} ms over {bars.get('max_p95_ms')} ms")
            if long_ > bars.get("max_long_share", 0.02):
                bad.append(f"{long_:.1%} of frames at or over {bars.get('long_frame_ms')} ms")
            if bad and software:
                self.emit("frame-stability", None, "blocked", "; ".join(bad) + f" - on a software "
                          f"rasterizer ({renderer}), which cannot draw the game at speed: "
                          "re-measure on a GPU host", data)
            elif bad:
                self.emit("frame-stability", None, "fail", "; ".join(bad), data)
            else:
                self.emit("frame-stability", None, "pass", f"p95 {p95:.1f} ms, median "
                          f"{data['median_ms']} ms, {long_:.1%} long frames over {len(deltas)} "
                          f"frames ({renderer or 'renderer unknown'})", data)
        series = [p for p in (perf.get("memory") or {}).get("series") or []
                  if isinstance(p.get("mb"), (int, float))]
        bar = (self.bars.get("memory") or {}).get("max_growth_mb", 24)
        if len(series) < 2:
            self.emit("memory-growth", None, "blocked", "the heap was not read twice during play", data)
        else:
            growth = series[-1]["mb"] - series[0]["mb"]
            data.update(series=series, growth_mb=round(growth, 2))
            if growth > bar:
                self.emit("memory-growth", None, "fail", f"the heap grew {growth:.1f} MB over "
                          f"{series[-1]['ms'] / 1000:.0f} s (bar {bar} MB)", data)
            else:
                self.emit("memory-growth", None, "pass", f"{series[0]['mb']} -> {series[-1]['mb']} MB "
                          f"over {series[-1]['ms'] / 1000:.0f} s", data)

    def assets(self):
        bars = self.bars.get("assets") or {}
        images = self.bundle.get("images") or []
        audio = self.bundle.get("audio") or []
        if not images and not audio:
            self.emit("oversized-textures", None, "unmeasured", "no image or audio file in the bundle")
            self.emit("asset-weight", None, "unmeasured", "no image or audio file in the bundle")
            return
        big = [f"{i['path']} {i['width']}x{i['height']}" for i in images
               if max(i.get("width") or 0, i.get("height") or 0) > bars.get("texture_max_edge_px", 4096)]
        self.emit("oversized-textures", None, "fail" if big else "pass",
                  ("over the edge bar: " + ", ".join(big[:6])) if big else
                  f"{len(images)} image(s), largest edge "
                  f"{max([max(i.get('width') or 0, i.get('height') or 0) for i in images] or [0])} px",
                  {"oversized": big})
        heavy = [f"{i['path']} {i['width']}x{i['height']}" for i in images
                 if max(i.get("width") or 0, i.get("height") or 0) > bars.get("texture_warn_edge_px", 2048)]
        heavy += [f"{i['path']} {i['bytes'] // 1024} KiB" for i in images
                  if i["bytes"] > bars.get("image_max_bytes", 1048576)]
        oneshot = (self.bars.get("audio") or {}).get("oneshot_max_s", 6)
        for a in audio:
            seconds = a.get("duration_s")
            if seconds and seconds > oneshot:
                # Music (anything longer than a one-shot): judged by its bit rate.
                kbps = a["bytes"] * 8 / seconds / 1000
                if kbps > bars.get("music_max_kbps", 256):
                    heavy.append(f"{a['path']} {kbps:.0f} kbps")
                continue
            if a["bytes"] > bars.get("sfx_max_bytes", 524288):
                heavy.append(f"{a['path']} {a['bytes'] // 1024} KiB")
        self.emit("asset-weight", None, "fail" if heavy else "pass",
                  ("heavier than the bars: " + ", ".join(heavy[:6])) if heavy else
                  f"{len(images)} image(s) and {len(audio)} audio file(s) within the bars",
                  {"heavy": heavy[:30]})


def gated_loudness(blocks_db, gate):
    """10 log10 of the mean power of the 50 ms blocks louder than `gate` dBFS; None if none."""
    powers = [10 ** (b / 10.0) for b in blocks_db if isinstance(b, (int, float)) and b > gate]
    if not powers:
        return None
    return round(10 * math.log10(sum(powers) / len(powers)), 2)


def omission_policy(tier, klass):
    """The skipped-check rule (wgflib.check_strength) for the run's quality tier; with no
    tier known, from its class alone (strict when the class is under `not_passed_at`)."""
    if tier is not None:
        return check_strength.for_tier(tier, QUALITY_POLICY)
    block = (load_file(QUALITY_POLICY) or {}).get("skipped_checks") or {}
    strict = klass is not None and klass in (block.get("not_passed_at") or ())
    return check_strength.SkipPolicy(None, klass, strict, block.get("optional") or ())


def judge(records, contract, *, klass=None, hard_profiles=(), bundle=None,
          records_path=WORK_DIR + "/out", action_audio=None, design=None, tier=None):
    """Every check of the contract, from the spec's records: a list of Check."""
    j = _Judge(contract, klass, hard_profiles, bundle, records_path,
               skip=omission_policy(tier, klass))
    viewports = contract.get("viewports") or []
    outcome_viewports = (contract.get("outcomes") or {}).get("viewports") or []
    for v in viewports:
        j.viewport(v["id"], records.get(v["id"]) or {}, (v["width"], v["height"]))
    for vid in outcome_viewports:
        j.outcomes(vid, records.get(vid) or {})
    audio_vp = contract.get("audio_viewport")
    if action_audio is None:
        action_audio = settings(contract, design)["action_audio"]
    clips_record = (records.get(audio_vp) or {}).get("clips")
    j.audio(audio_vp, records.get(audio_vp) or {}, clips_record, action_audio)
    j.clips(clips_record)
    perf_vp = contract.get("perf_viewport")
    j.perf(perf_vp, (records.get(perf_vp) or {}).get("perf"))
    j.assets()
    return j.out


# -- small helpers ------------------------------------------------------------------------

def _path(url):
    if not url:
        return ""
    text = str(url)
    text = re.sub(r"^[a-z]+://[^/]+", "", text)
    return text.split("?", 1)[0].split("#", 1)[0]


def _asset_key(url):
    """A runtime asset's path below assets/: the manifest's relative url and the page's
    absolute one name the same file."""
    path = _path(url)
    if "/assets/" in path:
        path = path.split("/assets/", 1)[1]
    return path.lstrip("/").lstrip("./")


def _same_origin(url, origin):
    if not url or not origin:
        return not url or not origin
    return str(url).startswith(origin)


def _in_page(watch, key):
    """What the page itself recorded (sounds, context losses, rejections), over every page
    the test navigated to: each is kept under `runs` before the next navigation."""
    watch = watch if isinstance(watch, dict) else {}
    found = []
    for run in (watch.get("runs") or {}).values():
        found += (run or {}).get(key) or []
    return found


def _origin(watch):
    for run in ((watch or {}).get("runs") or {}).values():
        if isinstance(run, dict) and run.get("origin"):
            return run["origin"]
    return ""


def _favicon(url):
    return _path(url).endswith("/favicon.ico")


def _secs(ms):
    return "never" if ms is None else f"{ms / 1000:.2f} s"


def _overlap(a, b):
    w = min(a[0] + a[2], b[0] + b[2]) - max(a[0], b[0])
    h = min(a[1] + a[3], b[1] + b[3]) - max(a[1], b[1])
    return w * h if w > 0 and h > 0 else 0


def _level(audio):
    if not isinstance(audio, dict):
        return None
    level = audio.get("level")
    return round(level, 5) if isinstance(level, (int, float)) else None


def _sound_within(sounds, t, window, lead=20):
    """A sound started from `lead` ms before `t` to `window` ms after it."""
    if not isinstance(t, (int, float)) or t < 0:
        return False
    return any(t - max(lead, 20) <= s <= t + window for s in sounds)


def _percentile(values, q):
    ordered = sorted(values)
    k = (len(ordered) - 1) * q / 100.0
    lo, hi = math.floor(k), math.ceil(k)
    if lo == hi:
        return ordered[int(k)]
    return ordered[lo] + (ordered[hi] - ordered[lo]) * (k - lo)
