"""MV-4's browser session: real-browser evidence, taken on the bytes that would ship.

    python scripts/mv4/session.py --repo ../tower-merge-rush --out docs/evidence/mv-4/...

What it does, in order:

1. A scratch clone of the game repository at its HEAD (`git clone`, local, no network), so the
   game repository is never touched.
2. Dependencies from the local pnpm store (`pnpm install --frozen-lockfile --offline`).
3. The bundle. With `--release <id>`, the target platform's zip from `release/<id>/` is checked
   against `packages.json`'s sha256 and unpacked as `dist/`, so the bytes measured are the bytes
   that would ship. Without it, a fresh `pnpm build` of the commit. The evidence says which.
4. session.spec.ts, per project: a real desktop Chromium, and a device-descriptor project whose
   results are labelled `emulated-mobile` and can never be reported as a device measurement.

Every child goes through wgflib.procs, so nothing it starts outlives it. The harness never
decides a criterion: it records measurements, their class, and the checks' own verdicts.
"""

import argparse
import hashlib
import json
import os
import shutil
import socket
import sys
import zipfile

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

from wgflib import procs, template_contract as contract, yamllite  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC = os.path.join(HERE, "session.spec.ts")

CONFIG = """\
// Generated by the Factory's MV-4 evidence harness (scripts/mv4/session.py) in a scratch
// clone. Serves the bundle under dist/ with the repository's own `pnpm preview`.
import {{ defineConfig, devices }} from "@playwright/test";

export default defineConfig({{
  testDir: "tests/mv4",
  outputDir: "test-results/mv4",
  workers: 1,
  retries: 0,
  timeout: 300_000,
  reporter: [["list"]],
  use: {{
    baseURL: "http://localhost:{port}",
    // Headed, because two of the things MV-4 measures are only real in a real window: a tab
    // that is genuinely hidden (headless Chromium reports visibilityState "visible" however
    // the pages are ordered), and a heap number that is not bucketed.
    headless: {headless},
    launchOptions: {{
      args: ["--enable-precise-memory-info"],
      // Playwright's defaults switch off exactly the behaviour a hidden tab is made of, so a
      // test browser never backgrounds a page the way a player's browser does. Dropping them
      // is what makes `document.visibilityState` report "hidden" when the window is minimised.
      // `--no-startup-window` was dropped too, to give the tab strip a second tab needs. It is
      // kept now: with a startup window the browser closed under the third project mid-sample
      // ("Target page, context or browser has been closed"), and the tab it bought still left
      // the page reporting "visible". A harness that loses a session is worse than a check that
      // says UNVERIFIED.
      ignoreDefaultArgs: [
        "--disable-backgrounding-occluded-windows",
        "--disable-renderer-backgrounding",
        "--disable-background-timer-throttling",
      ],
    }},
  }},
  projects: [
    {{ name: "desktop-real", use: {{ ...devices["Desktop Chrome"] }} }},
    {{ name: "mobile-emulated", use: {{ ...devices["Pixel 5"] }} }},
    {{ name: "mobile-emulated-throttled", use: {{ ...devices["Pixel 5"] }} }},
  ],
  webServer: {{
    command: "pnpm preview --port {port} --strictPort",
    port: {port},
    reuseExistingServer: false,
    timeout: 120_000,
  }},
}});
"""


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return "sha256:" + digest.hexdigest()


def free_port():
    with socket.socket() as probe:
        probe.bind(("127.0.0.1", 0))
        return probe.getsockname()[1]


def run(argv, cwd, timeout, env=None, log=None):
    result = procs.run(argv, cwd=cwd, timeout=timeout, env=env, log_path=log,
                       stderr_to_stdout=True)
    return {"argv": " ".join(argv), "status": result.status, "ok": result.ok,
            "returncode": result.returncode, "tail": result.tail(40) if not result.ok else None}


def target_platform(repo):
    """The platform this repository's single bundle boots, by the pinned template's own rule."""
    config = yamllite.load_file(os.path.join(repo, contract.GAME_CONFIG))
    return contract.build_target(config.get("platforms") or [])


def bundle_from_release(checkout, release_id, platform_id, evidence):
    """Unpack the target platform's released zip as dist/, after checking its recorded hash.

    A package the release never recorded, or one whose bytes do not match what was recorded,
    is refused: measuring it would be evidence about something that does not ship."""
    root = os.path.join(checkout, contract.RELEASE_ROOT, release_id)
    listed = os.path.join(root, os.path.basename(contract.RELEASE_PACKAGES))
    with open(listed, encoding="utf-8") as handle:
        packages = json.load(handle)
    entry = next((p for p in packages if p.get("platform_id") == platform_id), None)
    if entry is None:
        raise SystemExit(f"release {release_id} has no package for the build target "
                         f"{platform_id}; it lists {[p.get('platform_id') for p in packages]}")
    zip_path = os.path.join(root, entry["filename"])
    actual = sha256_file(zip_path)
    if actual != entry["checksum"]:
        raise SystemExit(f"{entry['filename']}: {actual} does not match the recorded "
                         f"{entry['checksum']}")
    dist = os.path.join(checkout, "dist")
    shutil.rmtree(dist, ignore_errors=True)
    with zipfile.ZipFile(zip_path) as archive:
        archive.extractall(dist)
    # A package may be zipped with or without a top-level directory; preview serves dist/.
    entries = os.listdir(dist)
    if len(entries) == 1 and os.path.isdir(os.path.join(dist, entries[0])):
        inner = os.path.join(dist, entries[0])
        for name in os.listdir(inner):
            shutil.move(os.path.join(inner, name), os.path.join(dist, name))
        os.rmdir(inner)
    evidence["bundle"] = {"source": "release-package", "release": release_id,
                          "platform_id": platform_id, "file": entry["filename"],
                          "sha256": actual, "size_mb": entry.get("size_mb")}
    return actual


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--repo", required=True, help="the game repository to measure")
    parser.add_argument("--out", required=True, help="where the evidence is written")
    parser.add_argument("--release", help="a release id under release/; its target platform's "
                                          "package is measured instead of a fresh build")
    parser.add_argument("--sample-seconds", type=int, default=20)
    parser.add_argument("--project", action="append",
                        help="limit to one Playwright project (repeatable)")
    parser.add_argument("--reuse-checkout", action="store_true",
                        help="reuse an existing scratch clone and its node_modules")
    parser.add_argument("--allow-host", action="append", default=[],
                        help="an external host the session may contact, for criterion D. "
                             "Each one is a deliberate, recorded outward request; without any, "
                             "every external request is aborted")
    parser.add_argument("--headless", action="store_true",
                        help="run without a window; the visibility and heap checks then "
                             "report UNVERIFIED rather than a result")
    args = parser.parse_args(argv)

    repo = os.path.abspath(args.repo)
    out = os.path.abspath(args.out)
    os.makedirs(out, exist_ok=True)
    checkout = os.path.join(out, "checkout")
    logs = os.path.join(out, "logs")
    os.makedirs(logs, exist_ok=True)

    head = procs.run(["git", "-C", repo, "rev-parse", "HEAD"], timeout=60)
    commit = (head.stdout or "").strip()
    evidence = {"repo": repo, "commit": commit, "steps": [],
                "harness": "scripts/mv4/session.py"}

    if not (args.reuse_checkout and os.path.isdir(os.path.join(checkout, ".git"))):
        shutil.rmtree(checkout, ignore_errors=True)
        evidence["steps"].append(run(["git", "clone", "--no-hardlinks", repo, checkout],
                                    cwd=out, timeout=900, log=os.path.join(logs, "clone.log")))
        if not evidence["steps"][-1]["ok"]:
            raise SystemExit("clone failed: " + str(evidence["steps"][-1]["tail"]))
        evidence["steps"].append(run(["pnpm", "install", "--frozen-lockfile", "--offline"],
                                     cwd=checkout, timeout=1800,
                                     log=os.path.join(logs, "install.log")))
        if not evidence["steps"][-1]["ok"]:
            raise SystemExit("install failed: " + str(evidence["steps"][-1]["tail"]))

    platform_id = target_platform(checkout)
    evidence["build_target"] = platform_id

    if args.release:
        artifact_sha = bundle_from_release(checkout, args.release, platform_id, evidence)
    else:
        evidence["steps"].append(run(["pnpm", "build"], cwd=checkout, timeout=1800,
                                     log=os.path.join(logs, "build.log")))
        if not evidence["steps"][-1]["ok"]:
            raise SystemExit("build failed: " + str(evidence["steps"][-1]["tail"]))
        # Hash the built tree, so the measurement names the bytes it was taken on.
        digest = hashlib.sha256()
        for directory, dirs, files in os.walk(os.path.join(checkout, "dist")):
            dirs.sort()
            for name in sorted(files):
                path = os.path.join(directory, name)
                digest.update(os.path.relpath(path, checkout).replace(os.sep, "/").encode())
                digest.update(open(path, "rb").read())
        artifact_sha = "sha256:" + digest.hexdigest()
        evidence["bundle"] = {"source": "fresh-build", "platform_id": platform_id,
                              "sha256": artifact_sha}

    port = free_port()
    os.makedirs(os.path.join(checkout, "tests", "mv4"), exist_ok=True)
    shutil.copy(SPEC, os.path.join(checkout, "tests", "mv4", "session.spec.ts"))
    with open(os.path.join(checkout, "playwright.mv4.config.ts"), "w", encoding="utf-8") as h:
        h.write(CONFIG.format(port=port,
                              headless="true" if args.headless else "false"))

    # An earlier run's session files are not evidence about this one. A run limited to one
    # project would otherwise collect the other projects' previous results as its own, and the
    # summary would name three measurements where one was taken.
    sessions = os.path.join(out, "sessions")
    shutil.rmtree(sessions, ignore_errors=True)
    env = dict(os.environ, WGF_MV4_OUT=sessions, WGF_MV4_ARTIFACT=evidence["bundle"]["source"],
               WGF_MV4_ARTIFACT_SHA=artifact_sha, WGF_MV4_SAMPLE_S=str(args.sample_seconds),
               WGF_MV4_ALLOW_HOSTS=",".join(args.allow_host))
    evidence["allowed_hosts"] = list(args.allow_host)
    command = ["pnpm", "exec", "playwright", "test", "-c", "playwright.mv4.config.ts"]
    for project in args.project or []:
        command += ["--project", project]
    evidence["steps"].append(run(command, cwd=checkout, timeout=1800, env=env,
                                 log=os.path.join(logs, "session.log")))

    collected, telemetry = [], []
    for project in sorted(os.listdir(sessions)) if os.path.isdir(sessions) else []:
        path = os.path.join(sessions, project, "session.json")
        if not os.path.isfile(path):
            continue
        with open(path, encoding="utf-8") as handle:
            session = json.load(handle)
        collected.append(session)
        telemetry.append({"kind": "test-telemetry", "project": project, "commit": commit,
                          "artifact_sha256": artifact_sha,
                          "measurement_class": session.get("measurement_class"),
                          "collected": (session.get("telemetry") or {}).get("collected")})
    evidence["sessions"] = collected
    with open(os.path.join(out, "browser-session.json"), "w", encoding="utf-8") as handle:
        json.dump(evidence, handle, indent=2)
        handle.write("\n")
    with open(os.path.join(out, "telemetry.jsonl"), "w", encoding="utf-8") as handle:
        for record in telemetry:
            handle.write(json.dumps(record) + "\n")

    for session in collected:
        checks = session.get("checks") or {}
        failed = [cid for cid, c in checks.items() if c.get("status") == "FAIL"]
        print(f"{session['project']:16} {session['measurement_class']:24} "
              f"{len(checks)} checks, {len(failed)} FAIL" + (f": {failed}" if failed else ""))
    print(f"evidence: {out}")
    return 0 if evidence["steps"][-1]["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
